// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch(new java.lang.String[][] { new java.lang.String[] { "en_US", "Dutch" }, new java.lang.String[] { "de_DE", "Dutch" } }),
	English(new java.lang.String[][] { new java.lang.String[] { "en_US", "English" }, new java.lang.String[] { "de_DE", "English" } }),
	French(new java.lang.String[][] { new java.lang.String[] { "en_US", "French" }, new java.lang.String[] { "de_DE", "French" } }),
	German(new java.lang.String[][] { new java.lang.String[] { "en_US", "German" }, new java.lang.String[] { "de_DE", "German" } }),
	Hindi(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hindi" }, new java.lang.String[] { "de_DE", "Hindi" } }),
	Portuguese(new java.lang.String[][] { new java.lang.String[] { "en_US", "Portuguese" }, new java.lang.String[] { "de_DE", "Portuguese" } }),
	Spanish(new java.lang.String[][] { new java.lang.String[] { "en_US", "Spanish" }, new java.lang.String[] { "de_DE", "Spanish" } }),
	Turkish(new java.lang.String[][] { new java.lang.String[] { "en_US", "Turkish" }, new java.lang.String[] { "de_DE", "Turkish" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private TranslationLanguages(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "de_DE");
	}

	public java.lang.String getCaption()
	{
		return captions.get("de_DE");
	}
}
