// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original(new java.lang.String[][] { new java.lang.String[] { "en_US", "Original" }, new java.lang.String[] { "de_DE", "Original" } }),
	low(new java.lang.String[][] { new java.lang.String[] { "en_US", "Low" }, new java.lang.String[] { "de_DE", "Low" } }),
	medium(new java.lang.String[][] { new java.lang.String[] { "en_US", "Medium" }, new java.lang.String[] { "de_DE", "Medium" } }),
	high(new java.lang.String[][] { new java.lang.String[] { "en_US", "High" }, new java.lang.String[] { "de_DE", "High" } }),
	custom(new java.lang.String[][] { new java.lang.String[] { "en_US", "Custom" }, new java.lang.String[] { "de_DE", "Custom" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private PictureQuality(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "de_DE");
	}

	public java.lang.String getCaption()
	{
		return captions.get("de_DE");
	}
}
