// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Fels module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCO_Einsatz_SaveSondereintragBuilder(
		fels.proxies.Einsatz _sondereinsatz,
		fels.proxies.EinsatzHelper _einsatzHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACO_Einsatz_SaveSondereintrag");
		builder = builder.withParam("Sondereinsatz", _sondereinsatz);
		builder = builder.withParam("EinsatzHelper", _einsatzHelper);
		return builder;
	}

	public static void aCO_Einsatz_SaveSondereintrag(
		IContext context,
		fels.proxies.Einsatz _sondereinsatz,
		fels.proxies.EinsatzHelper _einsatzHelper
	)
	{
		aCO_Einsatz_SaveSondereintragBuilder(
				_sondereinsatz,
				_einsatzHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCO_Einsatz_SetTitelBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACO_Einsatz_SetTitel");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCO_Einsatz_SetTitel(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCO_Einsatz_SetTitelBuilder(
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCO_Schacht_CalculateAttributesBuilder(
		fels.proxies.Schacht _schacht
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACO_Schacht_CalculateAttributes");
		builder = builder.withParam("Schacht", _schacht);
		return builder;
	}

	public static void aCO_Schacht_CalculateAttributes(
		IContext context,
		fels.proxies.Schacht _schacht
	)
	{
		aCO_Schacht_CalculateAttributesBuilder(
				_schacht
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Dichtheitspruefung_PrintBuilder(
		fels.proxies.Schacht _schacht
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Dichtheitspruefung_Print");
		builder = builder.withParam("Schacht", _schacht);
		return builder;
	}

	public static void aCT_Dichtheitspruefung_Print(
		IContext context,
		fels.proxies.Schacht _schacht
	)
	{
		aCT_Dichtheitspruefung_PrintBuilder(
				_schacht
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Dichtheitspruefung_PrintTotalBuilder(
		fels.proxies.Auftrag _auftrag
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Dichtheitspruefung_PrintTotal");
		builder = builder.withParam("Auftrag", _auftrag);
		return builder;
	}

	public static void aCT_Dichtheitspruefung_PrintTotal(
		IContext context,
		fels.proxies.Auftrag _auftrag
	)
	{
		aCT_Dichtheitspruefung_PrintTotalBuilder(
				_auftrag
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Einsatz_ClickInCalendarBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Einsatz_ClickInCalendar");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Einsatz_ClickInCalendar(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Einsatz_ClickInCalendarBuilder(
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Einsatz_CreateBuilder(
		fels.proxies.EinsatzHelper _einsatzHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Einsatz_Create");
		builder = builder.withParam("EinsatzHelper", _einsatzHelper);
		return builder;
	}

	public static void aCT_Einsatz_Create(
		IContext context,
		fels.proxies.EinsatzHelper _einsatzHelper
	)
	{
		aCT_Einsatz_CreateBuilder(
				_einsatzHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Einsatz_DateSelectionBuilder(
		java.util.Date _start
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Einsatz_DateSelection");
		builder = builder.withParam("Start", _start);
		return builder;
	}

	public static void aCT_Einsatz_DateSelection(
		IContext context,
		java.util.Date _start
	)
	{
		aCT_Einsatz_DateSelectionBuilder(
				_start
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Einsatz_PersonalEreignisBuilder(
		administration.proxies.Account _account
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Einsatz_PersonalEreignis");
		builder = builder.withParam("Account", _account);
		return builder;
	}

	public static void aCT_Einsatz_PersonalEreignis(
		IContext context,
		administration.proxies.Account _account
	)
	{
		aCT_Einsatz_PersonalEreignisBuilder(
				_account
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Einsatz_PrintBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Einsatz_Print");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Einsatz_Print(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Einsatz_PrintBuilder(
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Einsatz_PrintLeistungsbereicheBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Einsatz_PrintLeistungsbereiche");
		return builder;
	}

	public static void aCT_Einsatz_PrintLeistungsbereiche(IContext context)
	{
		aCT_Einsatz_PrintLeistungsbereicheBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Foto_ForNebelprotokollBuilder(
		fels.proxies.Nebelprotokoll _nebelprotokoll
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Foto_ForNebelprotokoll");
		builder = builder.withParam("Nebelprotokoll", _nebelprotokoll);
		return builder;
	}

	public static void aCT_Foto_ForNebelprotokoll(
		IContext context,
		fels.proxies.Nebelprotokoll _nebelprotokoll
	)
	{
		aCT_Foto_ForNebelprotokollBuilder(
				_nebelprotokoll
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Leistung_AddToEinsatzBuilder(
		fels.proxies.Einsatz _einsatz,
		java.util.List<fels.proxies.Leistung> _leistungList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Leistung_AddToEinsatz");
		builder = builder.withParam("Einsatz", _einsatz);
		builder = builder.withParam("LeistungList", _leistungList);
		return builder;
	}

	public static void aCT_Leistung_AddToEinsatz(
		IContext context,
		fels.proxies.Einsatz _einsatz,
		java.util.List<fels.proxies.Leistung> _leistungList
	)
	{
		aCT_Leistung_AddToEinsatzBuilder(
				_einsatz,
				_leistungList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Leistung_OnSelectionChangeBuilder(
		fels.proxies.Einsatz _einsatz,
		java.util.List<fels.proxies.Leistung> _leistungList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Leistung_OnSelectionChange");
		builder = builder.withParam("Einsatz", _einsatz);
		builder = builder.withParam("LeistungList", _leistungList);
		return builder;
	}

	public static void aCT_Leistung_OnSelectionChange(
		IContext context,
		fels.proxies.Einsatz _einsatz,
		java.util.List<fels.proxies.Leistung> _leistungList
	)
	{
		aCT_Leistung_OnSelectionChangeBuilder(
				_einsatz,
				_leistungList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Leistung_RemoveFromEinsatzBuilder(
		fels.proxies.ErbrachteLeistung _erbrachteLeistung,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Leistung_RemoveFromEinsatz");
		builder = builder.withParam("ErbrachteLeistung", _erbrachteLeistung);
		builder = builder.withParam("Leistung", _leistung);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Leistung_RemoveFromEinsatz(
		IContext context,
		fels.proxies.ErbrachteLeistung _erbrachteLeistung,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Leistung_RemoveFromEinsatzBuilder(
				_erbrachteLeistung,
				_leistung,
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Leistung_RemoveFromEinsatz__MobileBuilder(
		fels.proxies.ErbrachteLeistung _erbrachteLeistung,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Leistung_RemoveFromEinsatz__Mobile");
		builder = builder.withParam("ErbrachteLeistung", _erbrachteLeistung);
		builder = builder.withParam("Leistung", _leistung);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Leistung_RemoveFromEinsatz__Mobile(
		IContext context,
		fels.proxies.ErbrachteLeistung _erbrachteLeistung,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Leistung_RemoveFromEinsatz__MobileBuilder(
				_erbrachteLeistung,
				_leistung,
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Leistung_SaveBuilder(
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Leistung_Save");
		builder = builder.withParam("Leistung", _leistung);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Leistung_Save(
		IContext context,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Leistung_SaveBuilder(
				_leistung,
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Leistung_Save__MobileBuilder(
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz,
		fels.proxies.ErbrachteLeistung _erbrachteLeistung
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Leistung_Save__Mobile");
		builder = builder.withParam("Leistung", _leistung);
		builder = builder.withParam("Einsatz", _einsatz);
		builder = builder.withParam("ErbrachteLeistung", _erbrachteLeistung);
		return builder;
	}

	public static void aCT_Leistung_Save__Mobile(
		IContext context,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz,
		fels.proxies.ErbrachteLeistung _erbrachteLeistung
	)
	{
		aCT_Leistung_Save__MobileBuilder(
				_leistung,
				_einsatz,
				_erbrachteLeistung
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_LeistungHelper_CreateLeistungBuilder(
		fels.proxies.LeistungHelper _leistungHelper,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_LeistungHelper_CreateLeistung");
		builder = builder.withParam("LeistungHelper", _leistungHelper);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_LeistungHelper_CreateLeistung(
		IContext context,
		fels.proxies.LeistungHelper _leistungHelper,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_LeistungHelper_CreateLeistungBuilder(
				_leistungHelper,
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Mitarbeiter_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Mitarbeiter_Create");
		return builder;
	}

	public static void aCT_Mitarbeiter_Create(IContext context)
	{
		aCT_Mitarbeiter_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Nebelprotokoll_CreateBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Nebelprotokoll_Create");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Nebelprotokoll_Create(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Nebelprotokoll_CreateBuilder(
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Nebelprotokoll_PrintBuilder(
		fels.proxies.Nebelprotokoll _nebelprotokoll
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Nebelprotokoll_Print");
		builder = builder.withParam("Nebelprotokoll", _nebelprotokoll);
		return builder;
	}

	public static void aCT_Nebelprotokoll_Print(
		IContext context,
		fels.proxies.Nebelprotokoll _nebelprotokoll
	)
	{
		aCT_Nebelprotokoll_PrintBuilder(
				_nebelprotokoll
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Schacht_CreateBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Schacht_Create");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Schacht_Create(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Schacht_CreateBuilder(
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Schacht_Create__MobileBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Schacht_Create__Mobile");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Schacht_Create__Mobile(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Schacht_Create__MobileBuilder(
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Signature_ResetSignatureBuilder(
		fels.proxies.Signature _signature,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Signature_ResetSignature");
		builder = builder.withParam("Signature", _signature);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void aCT_Signature_ResetSignature(
		IContext context,
		fels.proxies.Signature _signature,
		fels.proxies.Einsatz _einsatz
	)
	{
		aCT_Signature_ResetSignatureBuilder(
				_signature,
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Signature_SaveBuilder(
		fels.proxies.Signature _signature
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.ACT_Signature_Save");
		builder = builder.withParam("Signature", _signature);
		return builder;
	}

	public static void aCT_Signature_Save(
		IContext context,
		fels.proxies.Signature _signature
	)
	{
		aCT_Signature_SaveBuilder(
				_signature
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bDE_Leistungsabrechnung_DeleteBemerkungBuilder(
		fels.proxies.Leistungsabrechnung _leistungsabrechnung
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.BDE_Leistungsabrechnung_DeleteBemerkung");
		builder = builder.withParam("Leistungsabrechnung", _leistungsabrechnung);
		return builder;
	}

	public static boolean bDE_Leistungsabrechnung_DeleteBemerkung(
		IContext context,
		fels.proxies.Leistungsabrechnung _leistungsabrechnung
	)
	{
		Object result = bDE_Leistungsabrechnung_DeleteBemerkungBuilder(
				_leistungsabrechnung
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dOC_Dichtheitspruefung_ShowBuilder(
		fels.proxies.Schacht _schacht
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DOC_Dichtheitspruefung_Show");
		builder = builder.withParam("Schacht", _schacht);
		return builder;
	}

	public static void dOC_Dichtheitspruefung_Show(
		IContext context,
		fels.proxies.Schacht _schacht
	)
	{
		dOC_Dichtheitspruefung_ShowBuilder(
				_schacht
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dOC_Dichtheitspruefung_ShowTotalBuilder(
		fels.proxies.Auftrag _auftrag
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DOC_Dichtheitspruefung_ShowTotal");
		builder = builder.withParam("Auftrag", _auftrag);
		return builder;
	}

	public static void dOC_Dichtheitspruefung_ShowTotal(
		IContext context,
		fels.proxies.Auftrag _auftrag
	)
	{
		dOC_Dichtheitspruefung_ShowTotalBuilder(
				_auftrag
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dOC_Einsatz_ShowBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DOC_Einsatz_Show");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void dOC_Einsatz_Show(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		dOC_Einsatz_ShowBuilder(
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dOC_Einsatz_ShowLeistunsgbereicheBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DOC_Einsatz_ShowLeistunsgbereiche");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static void dOC_Einsatz_ShowLeistunsgbereiche(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		dOC_Einsatz_ShowLeistunsgbereicheBuilder(
				_einsatz
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dOC_Nebelprotokoll_ShowBuilder(
		fels.proxies.Nebelprotokoll _nebelprotokoll
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DOC_Nebelprotokoll_Show");
		builder = builder.withParam("Nebelprotokoll", _nebelprotokoll);
		return builder;
	}

	public static void dOC_Nebelprotokoll_Show(
		IContext context,
		fels.proxies.Nebelprotokoll _nebelprotokoll
	)
	{
		dOC_Nebelprotokoll_ShowBuilder(
				_nebelprotokoll
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Auftrag_WithFilterBuilder(
		fels.proxies.AuftragFilter _auftragFilter
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Auftrag_WithFilter");
		builder = builder.withParam("AuftragFilter", _auftragFilter);
		return builder;
	}

	public static java.util.List<fels.proxies.Auftrag> dS_Auftrag_WithFilter(
		IContext context,
		fels.proxies.AuftragFilter _auftragFilter
	)
	{
		Object result = dS_Auftrag_WithFilterBuilder(
				_auftragFilter
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Auftrag.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_AuftragFilterBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_AuftragFilter");
		return builder;
	}

	public static fels.proxies.AuftragFilter dS_AuftragFilter(IContext context)
	{
		Object result = dS_AuftragFilterBuilder().execute(context);
		return result == null ? null : fels.proxies.AuftragFilter.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_AuftragFilter_ForLeistungsbereicheBuilder(
		fels.proxies.Auftrag _auftrag,
		fels.proxies.Leistungsbereich _leistungsbereich
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_AuftragFilter_ForLeistungsbereiche");
		builder = builder.withParam("Auftrag", _auftrag);
		builder = builder.withParam("Leistungsbereich", _leistungsbereich);
		return builder;
	}

	public static fels.proxies.AuftragFilter dS_AuftragFilter_ForLeistungsbereiche(
		IContext context,
		fels.proxies.Auftrag _auftrag,
		fels.proxies.Leistungsbereich _leistungsbereich
	)
	{
		Object result = dS_AuftragFilter_ForLeistungsbereicheBuilder(
				_auftrag,
				_leistungsbereich
			)
			.execute(context);
		return result == null ? null : fels.proxies.AuftragFilter.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Auftraggeber_GetForEinsatzBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Auftraggeber_GetForEinsatz");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static fels.proxies.Auftraggeber dS_Auftraggeber_GetForEinsatz(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_Auftraggeber_GetForEinsatzBuilder(
				_einsatz
			)
			.execute(context);
		return result == null ? null : fels.proxies.Auftraggeber.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_DrawHelper_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_DrawHelper_Create");
		return builder;
	}

	public static fels.proxies.DrawHelper dS_DrawHelper_Create(IContext context)
	{
		Object result = dS_DrawHelper_CreateBuilder().execute(context);
		return result == null ? null : fels.proxies.DrawHelper.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Einsatz_AuftragFilterBuilder(
		fels.proxies.EinsatzHelper _einsatzHelper,
		fels.proxies.Auftrag _auftrag
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Einsatz_AuftragFilter");
		builder = builder.withParam("EinsatzHelper", _einsatzHelper);
		builder = builder.withParam("Auftrag", _auftrag);
		return builder;
	}

	public static java.util.List<fels.proxies.Einsatz> dS_Einsatz_AuftragFilter(
		IContext context,
		fels.proxies.EinsatzHelper _einsatzHelper,
		fels.proxies.Auftrag _auftrag
	)
	{
		Object result = dS_Einsatz_AuftragFilterBuilder(
				_einsatzHelper,
				_auftrag
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Einsatz.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Einsatz_ForUserBuilder(
		administration.proxies.Account _account
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Einsatz_ForUser");
		builder = builder.withParam("Account", _account);
		return builder;
	}

	public static java.util.List<fels.proxies.Einsatz> dS_Einsatz_ForUser(
		IContext context,
		administration.proxies.Account _account
	)
	{
		Object result = dS_Einsatz_ForUserBuilder(
				_account
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Einsatz.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Einsatz_ForUserTodayBuilder(
		administration.proxies.Account _account
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Einsatz_ForUserToday");
		builder = builder.withParam("Account", _account);
		return builder;
	}

	public static java.util.List<fels.proxies.Einsatz> dS_Einsatz_ForUserToday(
		IContext context,
		administration.proxies.Account _account
	)
	{
		Object result = dS_Einsatz_ForUserTodayBuilder(
				_account
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Einsatz.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Einsatz_GetMitarbeiterBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Einsatz_GetMitarbeiter");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static java.util.List<fels.proxies.Arbeitszeit> dS_Einsatz_GetMitarbeiter(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_Einsatz_GetMitarbeiterBuilder(
				_einsatz
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Arbeitszeit.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Einsatz_TotalBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Einsatz_Total");
		return builder;
	}

	public static java.util.List<fels.proxies.Einsatz> dS_Einsatz_Total(IContext context)
	{
		Object result = dS_Einsatz_TotalBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Einsatz.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Einsatz_TotalFilterBuilder(
		fels.proxies.EinsatzHelper _einsatzHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Einsatz_TotalFilter");
		builder = builder.withParam("EinsatzHelper", _einsatzHelper);
		return builder;
	}

	public static java.util.List<fels.proxies.Einsatz> dS_Einsatz_TotalFilter(
		IContext context,
		fels.proxies.EinsatzHelper _einsatzHelper
	)
	{
		Object result = dS_Einsatz_TotalFilterBuilder(
				_einsatzHelper
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Einsatz.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_EinsatzHelper_CreateBuilder(
		fels.proxies.ENUM_EinsatzHelper_TimeFilter _eNUM_EinsatzHelper_TimeFilter,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_EinsatzHelper_Create");
		builder = builder.withParam("ENUM_EinsatzHelper_TimeFilter", _eNUM_EinsatzHelper_TimeFilter == null ? null : _eNUM_EinsatzHelper_TimeFilter.name());
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static fels.proxies.EinsatzHelper dS_EinsatzHelper_Create(
		IContext context,
		fels.proxies.ENUM_EinsatzHelper_TimeFilter _eNUM_EinsatzHelper_TimeFilter,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_EinsatzHelper_CreateBuilder(
				_eNUM_EinsatzHelper_TimeFilter,
				_einsatz
			)
			.execute(context);
		return result == null ? null : fels.proxies.EinsatzHelper.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Einsatzhelper_Next2DaysBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Einsatzhelper_Next2Days");
		return builder;
	}

	public static java.util.List<fels.proxies.EinsatzHelper> dS_Einsatzhelper_Next2Days(IContext context)
	{
		Object result = dS_Einsatzhelper_Next2DaysBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.EinsatzHelper.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ErrachteLeistung_GetBuilder(
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_ErrachteLeistung_Get");
		builder = builder.withParam("Leistung", _leistung);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static fels.proxies.ErbrachteLeistung dS_ErrachteLeistung_Get(
		IContext context,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_ErrachteLeistung_GetBuilder(
				_leistung,
				_einsatz
			)
			.execute(context);
		return result == null ? null : fels.proxies.ErbrachteLeistung.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ErrachteLeistung_Get_2Builder(
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_ErrachteLeistung_Get_2");
		builder = builder.withParam("Leistung", _leistung);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static fels.proxies.ErbrachteLeistung dS_ErrachteLeistung_Get_2(
		IContext context,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_ErrachteLeistung_Get_2Builder(
				_leistung,
				_einsatz
			)
			.execute(context);
		return result == null ? null : fels.proxies.ErbrachteLeistung.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Foto_NebelprotokollBuilder(
		fels.proxies.Nebelprotokoll _nebelprotokoll,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Foto_Nebelprotokoll");
		builder = builder.withParam("Nebelprotokoll", _nebelprotokoll);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static java.util.List<fels.proxies.Foto> dS_Foto_Nebelprotokoll(
		IContext context,
		fels.proxies.Nebelprotokoll _nebelprotokoll,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_Foto_NebelprotokollBuilder(
				_nebelprotokoll,
				_einsatz
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Foto.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetCurrentUserBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_GetCurrentUser");
		return builder;
	}

	public static administration.proxies.Account dS_GetCurrentUser(IContext context)
	{
		Object result = dS_GetCurrentUserBuilder().execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Leistungen_FilterBuilder(
		fels.proxies.LeistungHelper _leistungHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Leistungen_Filter");
		builder = builder.withParam("LeistungHelper", _leistungHelper);
		return builder;
	}

	public static java.util.List<fels.proxies.Leistung> dS_Leistungen_Filter(
		IContext context,
		fels.proxies.LeistungHelper _leistungHelper
	)
	{
		Object result = dS_Leistungen_FilterBuilder(
				_leistungHelper
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Leistung.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_LeistungHelperBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_LeistungHelper");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static fels.proxies.LeistungHelper dS_LeistungHelper(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_LeistungHelperBuilder(
				_einsatz
			)
			.execute(context);
		return result == null ? null : fels.proxies.LeistungHelper.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_LeistungHelper_CreateBuilder(
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_LeistungHelper_Create");
		builder = builder.withParam("Leistung", _leistung);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static fels.proxies.LeistungHelper dS_LeistungHelper_Create(
		IContext context,
		fels.proxies.Leistung _leistung,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_LeistungHelper_CreateBuilder(
				_leistung,
				_einsatz
			)
			.execute(context);
		return result == null ? null : fels.proxies.LeistungHelper.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_LeistungsabrechnungBuilder(
		fels.proxies.Position _position,
		fels.proxies.Leistungsbereich _leistungsbereich,
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Leistungsabrechnung");
		builder = builder.withParam("Position", _position);
		builder = builder.withParam("Leistungsbereich", _leistungsbereich);
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static fels.proxies.Leistungsabrechnung dS_Leistungsabrechnung(
		IContext context,
		fels.proxies.Position _position,
		fels.proxies.Leistungsbereich _leistungsbereich,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_LeistungsabrechnungBuilder(
				_position,
				_leistungsbereich,
				_einsatz
			)
			.execute(context);
		return result == null ? null : fels.proxies.Leistungsabrechnung.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_LeistungsbereichBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Leistungsbereich");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static java.util.List<fels.proxies.Leistungsbereich> dS_Leistungsbereich(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_LeistungsbereichBuilder(
				_einsatz
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Leistungsbereich.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Nebelprotokoll_TotalBuilder(
		fels.proxies.Auftrag _auftrag,
		fels.proxies.AuftragFilter _auftragFilter
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Nebelprotokoll_Total");
		builder = builder.withParam("Auftrag", _auftrag);
		builder = builder.withParam("AuftragFilter", _auftragFilter);
		return builder;
	}

	public static java.util.List<fels.proxies.Nebelprotokoll> dS_Nebelprotokoll_Total(
		IContext context,
		fels.proxies.Auftrag _auftrag,
		fels.proxies.AuftragFilter _auftragFilter
	)
	{
		Object result = dS_Nebelprotokoll_TotalBuilder(
				_auftrag,
				_auftragFilter
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Nebelprotokoll.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_PositionenForPDF_2Builder(
		fels.proxies.Auftrag _auftrag,
		fels.proxies.Leistungsbereich _leistungsbereich
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_PositionenForPDF_2");
		builder = builder.withParam("Auftrag", _auftrag);
		builder = builder.withParam("Leistungsbereich", _leistungsbereich);
		return builder;
	}

	public static java.util.List<fels.proxies.Position> dS_PositionenForPDF_2(
		IContext context,
		fels.proxies.Auftrag _auftrag,
		fels.proxies.Leistungsbereich _leistungsbereich
	)
	{
		Object result = dS_PositionenForPDF_2Builder(
				_auftrag,
				_leistungsbereich
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Position.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Schacht_WithFilterBuilder(
		fels.proxies.AuftragFilter _auftragFilter,
		fels.proxies.Auftrag _auftrag,
		fels.proxies.Dichtheitspruefung _dichtheitspruefung
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Schacht_WithFilter");
		builder = builder.withParam("AuftragFilter", _auftragFilter);
		builder = builder.withParam("Auftrag", _auftrag);
		builder = builder.withParam("Dichtheitspruefung", _dichtheitspruefung);
		return builder;
	}

	public static java.util.List<fels.proxies.Schacht> dS_Schacht_WithFilter(
		IContext context,
		fels.proxies.AuftragFilter _auftragFilter,
		fels.proxies.Auftrag _auftrag,
		fels.proxies.Dichtheitspruefung _dichtheitspruefung
	)
	{
		Object result = dS_Schacht_WithFilterBuilder(
				_auftragFilter,
				_auftrag,
				_dichtheitspruefung
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Schacht.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_SelectionHelper_CreateBuilder(
		fels.proxies.Einsatz _einsatz,
		java.util.List<fels.proxies.Leistung> _leistungList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_SelectionHelper_Create");
		builder = builder.withParam("Einsatz", _einsatz);
		builder = builder.withParam("LeistungList", _leistungList);
		return builder;
	}

	public static fels.proxies.SelectionHelper dS_SelectionHelper_Create(
		IContext context,
		fels.proxies.Einsatz _einsatz,
		java.util.List<fels.proxies.Leistung> _leistungList
	)
	{
		Object result = dS_SelectionHelper_CreateBuilder(
				_einsatz,
				_leistungList
			)
			.execute(context);
		return result == null ? null : fels.proxies.SelectionHelper.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Signature_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Signature_Create");
		return builder;
	}

	public static fels.proxies.Signature dS_Signature_Create(IContext context)
	{
		Object result = dS_Signature_CreateBuilder().execute(context);
		return result == null ? null : fels.proxies.Signature.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Signatures_EinsatzBuilder(
		fels.proxies.Einsatz _einsatz
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Signatures_Einsatz");
		builder = builder.withParam("Einsatz", _einsatz);
		return builder;
	}

	public static java.util.List<fels.proxies.Signature> dS_Signatures_Einsatz(
		IContext context,
		fels.proxies.Einsatz _einsatz
	)
	{
		Object result = dS_Signatures_EinsatzBuilder(
				_einsatz
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> fels.proxies.Signature.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Urlaubsfilter_CreateBuilder(
		fels.proxies.Mitarbeiter _mitarbeiter
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_Urlaubsfilter_Create");
		builder = builder.withParam("Mitarbeiter", _mitarbeiter);
		return builder;
	}

	public static fels.proxies.Urlaubsfilter dS_Urlaubsfilter_Create(
		IContext context,
		fels.proxies.Mitarbeiter _mitarbeiter
	)
	{
		Object result = dS_Urlaubsfilter_CreateBuilder(
				_mitarbeiter
			)
			.execute(context);
		return result == null ? null : fels.proxies.Urlaubsfilter.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_VisibilityHelper_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.DS_VisibilityHelper_Create");
		return builder;
	}

	public static fels.proxies.VisibilityHelper dS_VisibilityHelper_Create(IContext context)
	{
		Object result = dS_VisibilityHelper_CreateBuilder().execute(context);
		return result == null ? null : fels.proxies.VisibilityHelper.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_Foto_SaveBuilder(
		fels.proxies.Foto _foto
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.OCH_Foto_Save");
		builder = builder.withParam("Foto", _foto);
		return builder;
	}

	public static void oCH_Foto_Save(
		IContext context,
		fels.proxies.Foto _foto
	)
	{
		oCH_Foto_SaveBuilder(
				_foto
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder onSaveBuilder(
		fels.proxies.DrawHelper _drawHelper,
		fels.proxies.Foto _foto
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.OnSave");
		builder = builder.withParam("DrawHelper", _drawHelper);
		builder = builder.withParam("Foto", _foto);
		return builder;
	}

	public static void onSave(
		IContext context,
		fels.proxies.DrawHelper _drawHelper,
		fels.proxies.Foto _foto
	)
	{
		onSaveBuilder(
				_drawHelper,
				_foto
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sCE_Documents_DeleteBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.SCE_Documents_Delete");
		return builder;
	}

	public static void sCE_Documents_Delete(IContext context)
	{
		sCE_Documents_DeleteBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Leistungsabrechnung_HandleDeleteBuilder(
		fels.proxies.Position _position,
		fels.proxies.Leistungsbereich _leistungsbereich,
		fels.proxies.Einsatz _einsatz,
		fels.proxies.RefreshHelper _refreshHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.SUB_Leistungsabrechnung_HandleDelete");
		builder = builder.withParam("Position", _position);
		builder = builder.withParam("Leistungsbereich", _leistungsbereich);
		builder = builder.withParam("Einsatz", _einsatz);
		builder = builder.withParam("RefreshHelper", _refreshHelper);
		return builder;
	}

	public static void sUB_Leistungsabrechnung_HandleDelete(
		IContext context,
		fels.proxies.Position _position,
		fels.proxies.Leistungsbereich _leistungsbereich,
		fels.proxies.Einsatz _einsatz,
		fels.proxies.RefreshHelper _refreshHelper
	)
	{
		sUB_Leistungsabrechnung_HandleDeleteBuilder(
				_position,
				_leistungsbereich,
				_einsatz,
				_refreshHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Leistungsabrechnung_HandleSaveBuilder(
		fels.proxies.Position _position,
		fels.proxies.Leistungsbereich _leistungsbereich,
		fels.proxies.Einsatz _einsatz,
		fels.proxies.RefreshHelper _refreshHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.SUB_Leistungsabrechnung_HandleSave");
		builder = builder.withParam("Position", _position);
		builder = builder.withParam("Leistungsbereich", _leistungsbereich);
		builder = builder.withParam("Einsatz", _einsatz);
		builder = builder.withParam("RefreshHelper", _refreshHelper);
		return builder;
	}

	public static void sUB_Leistungsabrechnung_HandleSave(
		IContext context,
		fels.proxies.Position _position,
		fels.proxies.Leistungsbereich _leistungsbereich,
		fels.proxies.Einsatz _einsatz,
		fels.proxies.RefreshHelper _refreshHelper
	)
	{
		sUB_Leistungsabrechnung_HandleSaveBuilder(
				_position,
				_leistungsbereich,
				_einsatz,
				_refreshHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Leistungsabrechnung_SaveBuilder(
		fels.proxies.Leistungsabrechnung _leistungsabrechnung
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.SUB_Leistungsabrechnung_Save");
		builder = builder.withParam("Leistungsabrechnung", _leistungsabrechnung);
		return builder;
	}

	public static void sUB_Leistungsabrechnung_Save(
		IContext context,
		fels.proxies.Leistungsabrechnung _leistungsabrechnung
	)
	{
		sUB_Leistungsabrechnung_SaveBuilder(
				_leistungsabrechnung
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Mitarbeiter_InitBuilder(
		administration.proxies.Account _account
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Fels.SUB_Mitarbeiter_Init");
		builder = builder.withParam("Account", _account);
		return builder;
	}

	public static void sUB_Mitarbeiter_Init(
		IContext context,
		administration.proxies.Account _account
	)
	{
		sUB_Mitarbeiter_InitBuilder(
				_account
			)
			.execute(context);
	}
}
