// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Ansprechpartner implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ansprechpartnerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Ansprechpartner";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Email("Email"),
		Telefon("Telefon"),
		Ansprechpartner_Auftraggeber("Fels.Ansprechpartner_Auftraggeber");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ansprechpartner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Ansprechpartner(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ansprechpartnerMendixObject)
	{
		if (ansprechpartnerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, ansprechpartnerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.ansprechpartnerMendixObject = ansprechpartnerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Ansprechpartner initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Ansprechpartner(context, mendixObject);
	}

	public static fels.proxies.Ansprechpartner load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Ansprechpartner.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Ansprechpartner> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Ansprechpartner.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Telefon
	 */
	public final java.lang.Long getTelefon()
	{
		return getTelefon(getContext());
	}

	/**
	 * @param context
	 * @return value of Telefon
	 */
	public final java.lang.Long getTelefon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Telefon.toString());
	}

	/**
	 * Set value of Telefon
	 * @param telefon
	 */
	public final void setTelefon(java.lang.Long telefon)
	{
		setTelefon(getContext(), telefon);
	}

	/**
	 * Set value of Telefon
	 * @param context
	 * @param telefon
	 */
	public final void setTelefon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long telefon)
	{
		getMendixObject().setValue(context, MemberNames.Telefon.toString(), telefon);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Ansprechpartner_Auftraggeber
	 */
	public final fels.proxies.Auftraggeber getAnsprechpartner_Auftraggeber() throws com.mendix.core.CoreException
	{
		return getAnsprechpartner_Auftraggeber(getContext());
	}

	/**
	 * @param context
	 * @return value of Ansprechpartner_Auftraggeber
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Auftraggeber getAnsprechpartner_Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Auftraggeber result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ansprechpartner_Auftraggeber.toString());
		if (identifier != null) {
			result = fels.proxies.Auftraggeber.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Ansprechpartner_Auftraggeber
	 * @param ansprechpartner_auftraggeber
	 */
	public final void setAnsprechpartner_Auftraggeber(fels.proxies.Auftraggeber ansprechpartner_auftraggeber)
	{
		setAnsprechpartner_Auftraggeber(getContext(), ansprechpartner_auftraggeber);
	}

	/**
	 * Set value of Ansprechpartner_Auftraggeber
	 * @param context
	 * @param ansprechpartner_auftraggeber
	 */
	public final void setAnsprechpartner_Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Auftraggeber ansprechpartner_auftraggeber)
	{
		if (ansprechpartner_auftraggeber == null) {
			getMendixObject().setValue(context, MemberNames.Ansprechpartner_Auftraggeber.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Ansprechpartner_Auftraggeber.toString(), ansprechpartner_auftraggeber.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ansprechpartnerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Ansprechpartner that = (fels.proxies.Ansprechpartner) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
