// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Arbeitszeit implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject arbeitszeitMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Arbeitszeit";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Start("Start"),
		End("End"),
		Arbeitszeit_Mitarbeiter("Fels.Arbeitszeit_Mitarbeiter"),
		Arbeitszeit_Einsatz("Fels.Arbeitszeit_Einsatz");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Arbeitszeit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Arbeitszeit(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject arbeitszeitMendixObject)
	{
		if (arbeitszeitMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, arbeitszeitMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.arbeitszeitMendixObject = arbeitszeitMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Arbeitszeit initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Arbeitszeit(context, mendixObject);
	}

	public static fels.proxies.Arbeitszeit load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Arbeitszeit.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Arbeitszeit> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Arbeitszeit.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Start
	 */
	public final java.util.Date getStart()
	{
		return getStart(getContext());
	}

	/**
	 * @param context
	 * @return value of Start
	 */
	public final java.util.Date getStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Start.toString());
	}

	/**
	 * Set value of Start
	 * @param start
	 */
	public final void setStart(java.util.Date start)
	{
		setStart(getContext(), start);
	}

	/**
	 * Set value of Start
	 * @param context
	 * @param start
	 */
	public final void setStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date start)
	{
		getMendixObject().setValue(context, MemberNames.Start.toString(), start);
	}

	/**
	 * @return value of End
	 */
	public final java.util.Date getEnd()
	{
		return getEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of End
	 */
	public final java.util.Date getEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.End.toString());
	}

	/**
	 * Set value of End
	 * @param end
	 */
	public final void setEnd(java.util.Date end)
	{
		setEnd(getContext(), end);
	}

	/**
	 * Set value of End
	 * @param context
	 * @param end
	 */
	public final void setEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date end)
	{
		getMendixObject().setValue(context, MemberNames.End.toString(), end);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Arbeitszeit_Mitarbeiter
	 */
	public final fels.proxies.Mitarbeiter getArbeitszeit_Mitarbeiter() throws com.mendix.core.CoreException
	{
		return getArbeitszeit_Mitarbeiter(getContext());
	}

	/**
	 * @param context
	 * @return value of Arbeitszeit_Mitarbeiter
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Mitarbeiter getArbeitszeit_Mitarbeiter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Mitarbeiter result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Arbeitszeit_Mitarbeiter.toString());
		if (identifier != null) {
			result = fels.proxies.Mitarbeiter.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Arbeitszeit_Mitarbeiter
	 * @param arbeitszeit_mitarbeiter
	 */
	public final void setArbeitszeit_Mitarbeiter(fels.proxies.Mitarbeiter arbeitszeit_mitarbeiter)
	{
		setArbeitszeit_Mitarbeiter(getContext(), arbeitszeit_mitarbeiter);
	}

	/**
	 * Set value of Arbeitszeit_Mitarbeiter
	 * @param context
	 * @param arbeitszeit_mitarbeiter
	 */
	public final void setArbeitszeit_Mitarbeiter(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Mitarbeiter arbeitszeit_mitarbeiter)
	{
		if (arbeitszeit_mitarbeiter == null) {
			getMendixObject().setValue(context, MemberNames.Arbeitszeit_Mitarbeiter.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Arbeitszeit_Mitarbeiter.toString(), arbeitszeit_mitarbeiter.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Arbeitszeit_Einsatz
	 */
	public final fels.proxies.Einsatz getArbeitszeit_Einsatz() throws com.mendix.core.CoreException
	{
		return getArbeitszeit_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of Arbeitszeit_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getArbeitszeit_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Arbeitszeit_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Arbeitszeit_Einsatz
	 * @param arbeitszeit_einsatz
	 */
	public final void setArbeitszeit_Einsatz(fels.proxies.Einsatz arbeitszeit_einsatz)
	{
		setArbeitszeit_Einsatz(getContext(), arbeitszeit_einsatz);
	}

	/**
	 * Set value of Arbeitszeit_Einsatz
	 * @param context
	 * @param arbeitszeit_einsatz
	 */
	public final void setArbeitszeit_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz arbeitszeit_einsatz)
	{
		if (arbeitszeit_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.Arbeitszeit_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Arbeitszeit_Einsatz.toString(), arbeitszeit_einsatz.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return arbeitszeitMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Arbeitszeit that = (fels.proxies.Arbeitszeit) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
