// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Auftrag implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject auftragMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Auftrag";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Strasse("Strasse"),
		Postleitzahl("Postleitzahl"),
		Ort("Ort"),
		Beschreibung("Beschreibung"),
		Auftragsnummer("Auftragsnummer"),
		Farbe("Farbe"),
		Auftrag_Auftraggeber("Fels.Auftrag_Auftraggeber"),
		Auftrag_Ansprechpartner("Fels.Auftrag_Ansprechpartner");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Auftrag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Auftrag(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject auftragMendixObject)
	{
		if (auftragMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, auftragMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.auftragMendixObject = auftragMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Auftrag initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Auftrag(context, mendixObject);
	}

	public static fels.proxies.Auftrag load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Auftrag.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Auftrag> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Auftrag.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Strasse
	 */
	public final java.lang.String getStrasse()
	{
		return getStrasse(getContext());
	}

	/**
	 * @param context
	 * @return value of Strasse
	 */
	public final java.lang.String getStrasse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Strasse.toString());
	}

	/**
	 * Set value of Strasse
	 * @param strasse
	 */
	public final void setStrasse(java.lang.String strasse)
	{
		setStrasse(getContext(), strasse);
	}

	/**
	 * Set value of Strasse
	 * @param context
	 * @param strasse
	 */
	public final void setStrasse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String strasse)
	{
		getMendixObject().setValue(context, MemberNames.Strasse.toString(), strasse);
	}

	/**
	 * @return value of Postleitzahl
	 */
	public final java.lang.Integer getPostleitzahl()
	{
		return getPostleitzahl(getContext());
	}

	/**
	 * @param context
	 * @return value of Postleitzahl
	 */
	public final java.lang.Integer getPostleitzahl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Postleitzahl.toString());
	}

	/**
	 * Set value of Postleitzahl
	 * @param postleitzahl
	 */
	public final void setPostleitzahl(java.lang.Integer postleitzahl)
	{
		setPostleitzahl(getContext(), postleitzahl);
	}

	/**
	 * Set value of Postleitzahl
	 * @param context
	 * @param postleitzahl
	 */
	public final void setPostleitzahl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer postleitzahl)
	{
		getMendixObject().setValue(context, MemberNames.Postleitzahl.toString(), postleitzahl);
	}

	/**
	 * @return value of Ort
	 */
	public final java.lang.String getOrt()
	{
		return getOrt(getContext());
	}

	/**
	 * @param context
	 * @return value of Ort
	 */
	public final java.lang.String getOrt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ort.toString());
	}

	/**
	 * Set value of Ort
	 * @param ort
	 */
	public final void setOrt(java.lang.String ort)
	{
		setOrt(getContext(), ort);
	}

	/**
	 * Set value of Ort
	 * @param context
	 * @param ort
	 */
	public final void setOrt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ort)
	{
		getMendixObject().setValue(context, MemberNames.Ort.toString(), ort);
	}

	/**
	 * @return value of Beschreibung
	 */
	public final java.lang.String getBeschreibung()
	{
		return getBeschreibung(getContext());
	}

	/**
	 * @param context
	 * @return value of Beschreibung
	 */
	public final java.lang.String getBeschreibung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Beschreibung.toString());
	}

	/**
	 * Set value of Beschreibung
	 * @param beschreibung
	 */
	public final void setBeschreibung(java.lang.String beschreibung)
	{
		setBeschreibung(getContext(), beschreibung);
	}

	/**
	 * Set value of Beschreibung
	 * @param context
	 * @param beschreibung
	 */
	public final void setBeschreibung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String beschreibung)
	{
		getMendixObject().setValue(context, MemberNames.Beschreibung.toString(), beschreibung);
	}

	/**
	 * @return value of Auftragsnummer
	 */
	public final java.lang.String getAuftragsnummer()
	{
		return getAuftragsnummer(getContext());
	}

	/**
	 * @param context
	 * @return value of Auftragsnummer
	 */
	public final java.lang.String getAuftragsnummer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Auftragsnummer.toString());
	}

	/**
	 * Set value of Auftragsnummer
	 * @param auftragsnummer
	 */
	public final void setAuftragsnummer(java.lang.String auftragsnummer)
	{
		setAuftragsnummer(getContext(), auftragsnummer);
	}

	/**
	 * Set value of Auftragsnummer
	 * @param context
	 * @param auftragsnummer
	 */
	public final void setAuftragsnummer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String auftragsnummer)
	{
		getMendixObject().setValue(context, MemberNames.Auftragsnummer.toString(), auftragsnummer);
	}

	/**
	 * @return value of Farbe
	 */
	public final java.lang.String getFarbe()
	{
		return getFarbe(getContext());
	}

	/**
	 * @param context
	 * @return value of Farbe
	 */
	public final java.lang.String getFarbe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Farbe.toString());
	}

	/**
	 * Set value of Farbe
	 * @param farbe
	 */
	public final void setFarbe(java.lang.String farbe)
	{
		setFarbe(getContext(), farbe);
	}

	/**
	 * Set value of Farbe
	 * @param context
	 * @param farbe
	 */
	public final void setFarbe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String farbe)
	{
		getMendixObject().setValue(context, MemberNames.Farbe.toString(), farbe);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Auftrag_Auftraggeber
	 */
	public final fels.proxies.Auftraggeber getAuftrag_Auftraggeber() throws com.mendix.core.CoreException
	{
		return getAuftrag_Auftraggeber(getContext());
	}

	/**
	 * @param context
	 * @return value of Auftrag_Auftraggeber
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Auftraggeber getAuftrag_Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Auftraggeber result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Auftrag_Auftraggeber.toString());
		if (identifier != null) {
			result = fels.proxies.Auftraggeber.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Auftrag_Auftraggeber
	 * @param auftrag_auftraggeber
	 */
	public final void setAuftrag_Auftraggeber(fels.proxies.Auftraggeber auftrag_auftraggeber)
	{
		setAuftrag_Auftraggeber(getContext(), auftrag_auftraggeber);
	}

	/**
	 * Set value of Auftrag_Auftraggeber
	 * @param context
	 * @param auftrag_auftraggeber
	 */
	public final void setAuftrag_Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Auftraggeber auftrag_auftraggeber)
	{
		if (auftrag_auftraggeber == null) {
			getMendixObject().setValue(context, MemberNames.Auftrag_Auftraggeber.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Auftrag_Auftraggeber.toString(), auftrag_auftraggeber.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Auftrag_Ansprechpartner
	 */
	public final fels.proxies.Ansprechpartner getAuftrag_Ansprechpartner() throws com.mendix.core.CoreException
	{
		return getAuftrag_Ansprechpartner(getContext());
	}

	/**
	 * @param context
	 * @return value of Auftrag_Ansprechpartner
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Ansprechpartner getAuftrag_Ansprechpartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Ansprechpartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Auftrag_Ansprechpartner.toString());
		if (identifier != null) {
			result = fels.proxies.Ansprechpartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Auftrag_Ansprechpartner
	 * @param auftrag_ansprechpartner
	 */
	public final void setAuftrag_Ansprechpartner(fels.proxies.Ansprechpartner auftrag_ansprechpartner)
	{
		setAuftrag_Ansprechpartner(getContext(), auftrag_ansprechpartner);
	}

	/**
	 * Set value of Auftrag_Ansprechpartner
	 * @param context
	 * @param auftrag_ansprechpartner
	 */
	public final void setAuftrag_Ansprechpartner(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Ansprechpartner auftrag_ansprechpartner)
	{
		if (auftrag_ansprechpartner == null) {
			getMendixObject().setValue(context, MemberNames.Auftrag_Ansprechpartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Auftrag_Ansprechpartner.toString(), auftrag_ansprechpartner.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return auftragMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Auftrag that = (fels.proxies.Auftrag) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
