// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class AuftragFilter implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject auftragFilterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.AuftragFilter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AuftragFilter_Einsatz("Fels.AuftragFilter_Einsatz"),
		AuftragFilter_Leistungsbereich("Fels.AuftragFilter_Leistungsbereich"),
		AuftragFilter_Auftraggeber("Fels.AuftragFilter_Auftraggeber");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AuftragFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AuftragFilter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject auftragFilterMendixObject)
	{
		if (auftragFilterMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, auftragFilterMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.auftragFilterMendixObject = auftragFilterMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.AuftragFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.AuftragFilter(context, mendixObject);
	}

	public static fels.proxies.AuftragFilter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.AuftragFilter.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AuftragFilter_Einsatz
	 */
	public final fels.proxies.Einsatz getAuftragFilter_Einsatz() throws com.mendix.core.CoreException
	{
		return getAuftragFilter_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of AuftragFilter_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getAuftragFilter_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AuftragFilter_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AuftragFilter_Einsatz
	 * @param auftragfilter_einsatz
	 */
	public final void setAuftragFilter_Einsatz(fels.proxies.Einsatz auftragfilter_einsatz)
	{
		setAuftragFilter_Einsatz(getContext(), auftragfilter_einsatz);
	}

	/**
	 * Set value of AuftragFilter_Einsatz
	 * @param context
	 * @param auftragfilter_einsatz
	 */
	public final void setAuftragFilter_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz auftragfilter_einsatz)
	{
		if (auftragfilter_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.AuftragFilter_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AuftragFilter_Einsatz.toString(), auftragfilter_einsatz.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AuftragFilter_Leistungsbereich
	 */
	public final fels.proxies.Leistungsbereich getAuftragFilter_Leistungsbereich() throws com.mendix.core.CoreException
	{
		return getAuftragFilter_Leistungsbereich(getContext());
	}

	/**
	 * @param context
	 * @return value of AuftragFilter_Leistungsbereich
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Leistungsbereich getAuftragFilter_Leistungsbereich(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Leistungsbereich result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AuftragFilter_Leistungsbereich.toString());
		if (identifier != null) {
			result = fels.proxies.Leistungsbereich.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AuftragFilter_Leistungsbereich
	 * @param auftragfilter_leistungsbereich
	 */
	public final void setAuftragFilter_Leistungsbereich(fels.proxies.Leistungsbereich auftragfilter_leistungsbereich)
	{
		setAuftragFilter_Leistungsbereich(getContext(), auftragfilter_leistungsbereich);
	}

	/**
	 * Set value of AuftragFilter_Leistungsbereich
	 * @param context
	 * @param auftragfilter_leistungsbereich
	 */
	public final void setAuftragFilter_Leistungsbereich(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Leistungsbereich auftragfilter_leistungsbereich)
	{
		if (auftragfilter_leistungsbereich == null) {
			getMendixObject().setValue(context, MemberNames.AuftragFilter_Leistungsbereich.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AuftragFilter_Leistungsbereich.toString(), auftragfilter_leistungsbereich.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AuftragFilter_Auftraggeber
	 */
	public final fels.proxies.Auftraggeber getAuftragFilter_Auftraggeber() throws com.mendix.core.CoreException
	{
		return getAuftragFilter_Auftraggeber(getContext());
	}

	/**
	 * @param context
	 * @return value of AuftragFilter_Auftraggeber
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Auftraggeber getAuftragFilter_Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Auftraggeber result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AuftragFilter_Auftraggeber.toString());
		if (identifier != null) {
			result = fels.proxies.Auftraggeber.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AuftragFilter_Auftraggeber
	 * @param auftragfilter_auftraggeber
	 */
	public final void setAuftragFilter_Auftraggeber(fels.proxies.Auftraggeber auftragfilter_auftraggeber)
	{
		setAuftragFilter_Auftraggeber(getContext(), auftragfilter_auftraggeber);
	}

	/**
	 * Set value of AuftragFilter_Auftraggeber
	 * @param context
	 * @param auftragfilter_auftraggeber
	 */
	public final void setAuftragFilter_Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Auftraggeber auftragfilter_auftraggeber)
	{
		if (auftragfilter_auftraggeber == null) {
			getMendixObject().setValue(context, MemberNames.AuftragFilter_Auftraggeber.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AuftragFilter_Auftraggeber.toString(), auftragfilter_auftraggeber.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return auftragFilterMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.AuftragFilter that = (fels.proxies.AuftragFilter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
