// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Auftraggeber implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject auftraggeberMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Auftraggeber";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Bezeichnung("Bezeichnung"),
		Strasse("Strasse"),
		Postleitzahl("Postleitzahl"),
		Ort("Ort"),
		Berichtsform("Berichtsform");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject auftraggeberMendixObject)
	{
		if (auftraggeberMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, auftraggeberMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.auftraggeberMendixObject = auftraggeberMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Auftraggeber initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Auftraggeber(context, mendixObject);
	}

	public static fels.proxies.Auftraggeber load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Auftraggeber.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Auftraggeber> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Auftraggeber.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Bezeichnung
	 */
	public final java.lang.String getBezeichnung()
	{
		return getBezeichnung(getContext());
	}

	/**
	 * @param context
	 * @return value of Bezeichnung
	 */
	public final java.lang.String getBezeichnung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Bezeichnung.toString());
	}

	/**
	 * Set value of Bezeichnung
	 * @param bezeichnung
	 */
	public final void setBezeichnung(java.lang.String bezeichnung)
	{
		setBezeichnung(getContext(), bezeichnung);
	}

	/**
	 * Set value of Bezeichnung
	 * @param context
	 * @param bezeichnung
	 */
	public final void setBezeichnung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bezeichnung)
	{
		getMendixObject().setValue(context, MemberNames.Bezeichnung.toString(), bezeichnung);
	}

	/**
	 * @return value of Strasse
	 */
	public final java.lang.String getStrasse()
	{
		return getStrasse(getContext());
	}

	/**
	 * @param context
	 * @return value of Strasse
	 */
	public final java.lang.String getStrasse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Strasse.toString());
	}

	/**
	 * Set value of Strasse
	 * @param strasse
	 */
	public final void setStrasse(java.lang.String strasse)
	{
		setStrasse(getContext(), strasse);
	}

	/**
	 * Set value of Strasse
	 * @param context
	 * @param strasse
	 */
	public final void setStrasse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String strasse)
	{
		getMendixObject().setValue(context, MemberNames.Strasse.toString(), strasse);
	}

	/**
	 * @return value of Postleitzahl
	 */
	public final java.lang.Integer getPostleitzahl()
	{
		return getPostleitzahl(getContext());
	}

	/**
	 * @param context
	 * @return value of Postleitzahl
	 */
	public final java.lang.Integer getPostleitzahl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Postleitzahl.toString());
	}

	/**
	 * Set value of Postleitzahl
	 * @param postleitzahl
	 */
	public final void setPostleitzahl(java.lang.Integer postleitzahl)
	{
		setPostleitzahl(getContext(), postleitzahl);
	}

	/**
	 * Set value of Postleitzahl
	 * @param context
	 * @param postleitzahl
	 */
	public final void setPostleitzahl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer postleitzahl)
	{
		getMendixObject().setValue(context, MemberNames.Postleitzahl.toString(), postleitzahl);
	}

	/**
	 * @return value of Ort
	 */
	public final java.lang.String getOrt()
	{
		return getOrt(getContext());
	}

	/**
	 * @param context
	 * @return value of Ort
	 */
	public final java.lang.String getOrt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ort.toString());
	}

	/**
	 * Set value of Ort
	 * @param ort
	 */
	public final void setOrt(java.lang.String ort)
	{
		setOrt(getContext(), ort);
	}

	/**
	 * Set value of Ort
	 * @param context
	 * @param ort
	 */
	public final void setOrt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ort)
	{
		getMendixObject().setValue(context, MemberNames.Ort.toString(), ort);
	}

	/**
	 * Get value of Berichtsform
	 * @param berichtsform
	 */
	public final fels.proxies.ENUM_Auftraggeber_Berichtsform getBerichtsform()
	{
		return getBerichtsform(getContext());
	}

	/**
	 * @param context
	 * @return value of Berichtsform
	 */
	public final fels.proxies.ENUM_Auftraggeber_Berichtsform getBerichtsform(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Berichtsform.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_Auftraggeber_Berichtsform.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Berichtsform
	 * @param berichtsform
	 */
	public final void setBerichtsform(fels.proxies.ENUM_Auftraggeber_Berichtsform berichtsform)
	{
		setBerichtsform(getContext(), berichtsform);
	}

	/**
	 * Set value of Berichtsform
	 * @param context
	 * @param berichtsform
	 */
	public final void setBerichtsform(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_Auftraggeber_Berichtsform berichtsform)
	{
		if (berichtsform != null) {
			getMendixObject().setValue(context, MemberNames.Berichtsform.toString(), berichtsform.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Berichtsform.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return auftraggeberMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Auftraggeber that = (fels.proxies.Auftraggeber) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
