// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Dichtheitspruefung implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dichtheitspruefungMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Dichtheitspruefung";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Min("Min"),
		Max("Max"),
		PassedSchaechte("PassedSchaechte"),
		TotalScore("TotalScore"),
		Dichtheitspruefung_Auftrag("Fels.Dichtheitspruefung_Auftrag");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Dichtheitspruefung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Dichtheitspruefung(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dichtheitspruefungMendixObject)
	{
		if (dichtheitspruefungMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dichtheitspruefungMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dichtheitspruefungMendixObject = dichtheitspruefungMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Dichtheitspruefung initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Dichtheitspruefung(context, mendixObject);
	}

	public static fels.proxies.Dichtheitspruefung load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Dichtheitspruefung.initialize(context, mendixObject);
	}

	/**
	 * @return value of Min
	 */
	public final java.lang.Integer getMin()
	{
		return getMin(getContext());
	}

	/**
	 * @param context
	 * @return value of Min
	 */
	public final java.lang.Integer getMin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Min.toString());
	}

	/**
	 * Set value of Min
	 * @param min
	 */
	public final void setMin(java.lang.Integer min)
	{
		setMin(getContext(), min);
	}

	/**
	 * Set value of Min
	 * @param context
	 * @param min
	 */
	public final void setMin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer min)
	{
		getMendixObject().setValue(context, MemberNames.Min.toString(), min);
	}

	/**
	 * @return value of Max
	 */
	public final java.lang.Integer getMax()
	{
		return getMax(getContext());
	}

	/**
	 * @param context
	 * @return value of Max
	 */
	public final java.lang.Integer getMax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Max.toString());
	}

	/**
	 * Set value of Max
	 * @param max
	 */
	public final void setMax(java.lang.Integer max)
	{
		setMax(getContext(), max);
	}

	/**
	 * Set value of Max
	 * @param context
	 * @param max
	 */
	public final void setMax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer max)
	{
		getMendixObject().setValue(context, MemberNames.Max.toString(), max);
	}

	/**
	 * @return value of PassedSchaechte
	 */
	public final java.math.BigDecimal getPassedSchaechte()
	{
		return getPassedSchaechte(getContext());
	}

	/**
	 * @param context
	 * @return value of PassedSchaechte
	 */
	public final java.math.BigDecimal getPassedSchaechte(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PassedSchaechte.toString());
	}

	/**
	 * Set value of PassedSchaechte
	 * @param passedschaechte
	 */
	public final void setPassedSchaechte(java.math.BigDecimal passedschaechte)
	{
		setPassedSchaechte(getContext(), passedschaechte);
	}

	/**
	 * Set value of PassedSchaechte
	 * @param context
	 * @param passedschaechte
	 */
	public final void setPassedSchaechte(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal passedschaechte)
	{
		getMendixObject().setValue(context, MemberNames.PassedSchaechte.toString(), passedschaechte);
	}

	/**
	 * @return value of TotalScore
	 */
	public final java.math.BigDecimal getTotalScore()
	{
		return getTotalScore(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalScore
	 */
	public final java.math.BigDecimal getTotalScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalScore.toString());
	}

	/**
	 * Set value of TotalScore
	 * @param totalscore
	 */
	public final void setTotalScore(java.math.BigDecimal totalscore)
	{
		setTotalScore(getContext(), totalscore);
	}

	/**
	 * Set value of TotalScore
	 * @param context
	 * @param totalscore
	 */
	public final void setTotalScore(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalscore)
	{
		getMendixObject().setValue(context, MemberNames.TotalScore.toString(), totalscore);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Dichtheitspruefung_Auftrag
	 */
	public final fels.proxies.Auftrag getDichtheitspruefung_Auftrag() throws com.mendix.core.CoreException
	{
		return getDichtheitspruefung_Auftrag(getContext());
	}

	/**
	 * @param context
	 * @return value of Dichtheitspruefung_Auftrag
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Auftrag getDichtheitspruefung_Auftrag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Auftrag result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Dichtheitspruefung_Auftrag.toString());
		if (identifier != null) {
			result = fels.proxies.Auftrag.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Dichtheitspruefung_Auftrag
	 * @param dichtheitspruefung_auftrag
	 */
	public final void setDichtheitspruefung_Auftrag(fels.proxies.Auftrag dichtheitspruefung_auftrag)
	{
		setDichtheitspruefung_Auftrag(getContext(), dichtheitspruefung_auftrag);
	}

	/**
	 * Set value of Dichtheitspruefung_Auftrag
	 * @param context
	 * @param dichtheitspruefung_auftrag
	 */
	public final void setDichtheitspruefung_Auftrag(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Auftrag dichtheitspruefung_auftrag)
	{
		if (dichtheitspruefung_auftrag == null) {
			getMendixObject().setValue(context, MemberNames.Dichtheitspruefung_Auftrag.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Dichtheitspruefung_Auftrag.toString(), dichtheitspruefung_auftrag.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dichtheitspruefungMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Dichtheitspruefung that = (fels.proxies.Dichtheitspruefung) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
