// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class EinsatzHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject einsatzHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.EinsatzHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Start("Start"),
		End("End"),
		_ShowEndTime("_ShowEndTime"),
		SearchString("SearchString"),
		TimeFilter("TimeFilter"),
		_toggleView("_toggleView"),
		EinsatzView("EinsatzView"),
		DayPicker("DayPicker"),
		EinsatzHelper_Einsatz("Fels.EinsatzHelper_Einsatz");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EinsatzHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EinsatzHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject einsatzHelperMendixObject)
	{
		if (einsatzHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, einsatzHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.einsatzHelperMendixObject = einsatzHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.EinsatzHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.EinsatzHelper(context, mendixObject);
	}

	public static fels.proxies.EinsatzHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.EinsatzHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Start
	 */
	public final java.util.Date getStart()
	{
		return getStart(getContext());
	}

	/**
	 * @param context
	 * @return value of Start
	 */
	public final java.util.Date getStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Start.toString());
	}

	/**
	 * Set value of Start
	 * @param start
	 */
	public final void setStart(java.util.Date start)
	{
		setStart(getContext(), start);
	}

	/**
	 * Set value of Start
	 * @param context
	 * @param start
	 */
	public final void setStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date start)
	{
		getMendixObject().setValue(context, MemberNames.Start.toString(), start);
	}

	/**
	 * @return value of End
	 */
	public final java.util.Date getEnd()
	{
		return getEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of End
	 */
	public final java.util.Date getEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.End.toString());
	}

	/**
	 * Set value of End
	 * @param end
	 */
	public final void setEnd(java.util.Date end)
	{
		setEnd(getContext(), end);
	}

	/**
	 * Set value of End
	 * @param context
	 * @param end
	 */
	public final void setEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date end)
	{
		getMendixObject().setValue(context, MemberNames.End.toString(), end);
	}

	/**
	 * @return value of _ShowEndTime
	 */
	public final java.lang.Boolean get_ShowEndTime()
	{
		return get_ShowEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of _ShowEndTime
	 */
	public final java.lang.Boolean get_ShowEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._ShowEndTime.toString());
	}

	/**
	 * Set value of _ShowEndTime
	 * @param _showendtime
	 */
	public final void set_ShowEndTime(java.lang.Boolean _showendtime)
	{
		set_ShowEndTime(getContext(), _showendtime);
	}

	/**
	 * Set value of _ShowEndTime
	 * @param context
	 * @param _showendtime
	 */
	public final void set_ShowEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _showendtime)
	{
		getMendixObject().setValue(context, MemberNames._ShowEndTime.toString(), _showendtime);
	}

	/**
	 * @return value of SearchString
	 */
	public final java.lang.String getSearchString()
	{
		return getSearchString(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchString
	 */
	public final java.lang.String getSearchString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchString.toString());
	}

	/**
	 * Set value of SearchString
	 * @param searchstring
	 */
	public final void setSearchString(java.lang.String searchstring)
	{
		setSearchString(getContext(), searchstring);
	}

	/**
	 * Set value of SearchString
	 * @param context
	 * @param searchstring
	 */
	public final void setSearchString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchstring)
	{
		getMendixObject().setValue(context, MemberNames.SearchString.toString(), searchstring);
	}

	/**
	 * Get value of TimeFilter
	 * @param timefilter
	 */
	public final fels.proxies.ENUM_EinsatzHelper_TimeFilter getTimeFilter()
	{
		return getTimeFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeFilter
	 */
	public final fels.proxies.ENUM_EinsatzHelper_TimeFilter getTimeFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TimeFilter.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_EinsatzHelper_TimeFilter.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TimeFilter
	 * @param timefilter
	 */
	public final void setTimeFilter(fels.proxies.ENUM_EinsatzHelper_TimeFilter timefilter)
	{
		setTimeFilter(getContext(), timefilter);
	}

	/**
	 * Set value of TimeFilter
	 * @param context
	 * @param timefilter
	 */
	public final void setTimeFilter(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_EinsatzHelper_TimeFilter timefilter)
	{
		if (timefilter != null) {
			getMendixObject().setValue(context, MemberNames.TimeFilter.toString(), timefilter.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TimeFilter.toString(), null);
		}
	}

	/**
	 * @return value of _toggleView
	 */
	public final java.lang.Boolean get_toggleView()
	{
		return get_toggleView(getContext());
	}

	/**
	 * @param context
	 * @return value of _toggleView
	 */
	public final java.lang.Boolean get_toggleView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._toggleView.toString());
	}

	/**
	 * Set value of _toggleView
	 * @param _toggleview
	 */
	public final void set_toggleView(java.lang.Boolean _toggleview)
	{
		set_toggleView(getContext(), _toggleview);
	}

	/**
	 * Set value of _toggleView
	 * @param context
	 * @param _toggleview
	 */
	public final void set_toggleView(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _toggleview)
	{
		getMendixObject().setValue(context, MemberNames._toggleView.toString(), _toggleview);
	}

	/**
	 * Get value of EinsatzView
	 * @param einsatzview
	 */
	public final fels.proxies.ENUM_EinsatzHelper_EinsatzView getEinsatzView()
	{
		return getEinsatzView(getContext());
	}

	/**
	 * @param context
	 * @return value of EinsatzView
	 */
	public final fels.proxies.ENUM_EinsatzHelper_EinsatzView getEinsatzView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EinsatzView.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_EinsatzHelper_EinsatzView.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EinsatzView
	 * @param einsatzview
	 */
	public final void setEinsatzView(fels.proxies.ENUM_EinsatzHelper_EinsatzView einsatzview)
	{
		setEinsatzView(getContext(), einsatzview);
	}

	/**
	 * Set value of EinsatzView
	 * @param context
	 * @param einsatzview
	 */
	public final void setEinsatzView(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_EinsatzHelper_EinsatzView einsatzview)
	{
		if (einsatzview != null) {
			getMendixObject().setValue(context, MemberNames.EinsatzView.toString(), einsatzview.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EinsatzView.toString(), null);
		}
	}

	/**
	 * Get value of DayPicker
	 * @param daypicker
	 */
	public final fels.proxies.ENUM_EinsatzHelper_DayPicker getDayPicker()
	{
		return getDayPicker(getContext());
	}

	/**
	 * @param context
	 * @return value of DayPicker
	 */
	public final fels.proxies.ENUM_EinsatzHelper_DayPicker getDayPicker(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DayPicker.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_EinsatzHelper_DayPicker.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DayPicker
	 * @param daypicker
	 */
	public final void setDayPicker(fels.proxies.ENUM_EinsatzHelper_DayPicker daypicker)
	{
		setDayPicker(getContext(), daypicker);
	}

	/**
	 * Set value of DayPicker
	 * @param context
	 * @param daypicker
	 */
	public final void setDayPicker(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_EinsatzHelper_DayPicker daypicker)
	{
		if (daypicker != null) {
			getMendixObject().setValue(context, MemberNames.DayPicker.toString(), daypicker.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DayPicker.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EinsatzHelper_Einsatz
	 */
	public final fels.proxies.Einsatz getEinsatzHelper_Einsatz() throws com.mendix.core.CoreException
	{
		return getEinsatzHelper_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of EinsatzHelper_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getEinsatzHelper_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EinsatzHelper_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EinsatzHelper_Einsatz
	 * @param einsatzhelper_einsatz
	 */
	public final void setEinsatzHelper_Einsatz(fels.proxies.Einsatz einsatzhelper_einsatz)
	{
		setEinsatzHelper_Einsatz(getContext(), einsatzhelper_einsatz);
	}

	/**
	 * Set value of EinsatzHelper_Einsatz
	 * @param context
	 * @param einsatzhelper_einsatz
	 */
	public final void setEinsatzHelper_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz einsatzhelper_einsatz)
	{
		if (einsatzhelper_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.EinsatzHelper_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EinsatzHelper_Einsatz.toString(), einsatzhelper_einsatz.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return einsatzHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.EinsatzHelper that = (fels.proxies.EinsatzHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
