// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Einsatz implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject einsatzMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Einsatz";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Start("Start"),
		End("End"),
		Besonderheiten("Besonderheiten"),
		_Spuelen("_Spuelen"),
		_TVUntersuchung("_TVUntersuchung"),
		_Schachtaufnahme("_Schachtaufnahme"),
		_Dichtheitspruefung("_Dichtheitspruefung"),
		_Nebeln("_Nebeln"),
		_LageplanErstellung("_LageplanErstellung"),
		_DokuErstellung("_DokuErstellung"),
		_SonstigeArbeiten("_SonstigeArbeiten"),
		_allDay("_allDay"),
		_wholeDay("_wholeDay"),
		EinsatzType("EinsatzType"),
		CalendarTitel("CalendarTitel"),
		Abwesenheitsgrund("Abwesenheitsgrund"),
		_Open("_Open"),
		Einsatz_Auftrag("Fels.Einsatz_Auftrag"),
		Einsatz_Fahrzeug("Fels.Einsatz_Fahrzeug"),
		Einsatz_Mitarbeiter("Fels.Einsatz_Mitarbeiter"),
		Einsatz_Leistung("Fels.Einsatz_Leistung");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Einsatz(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Einsatz(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject einsatzMendixObject)
	{
		if (einsatzMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, einsatzMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.einsatzMendixObject = einsatzMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Einsatz initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Einsatz(context, mendixObject);
	}

	public static fels.proxies.Einsatz load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Einsatz.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Einsatz> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Einsatz.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Start
	 */
	public final java.util.Date getStart()
	{
		return getStart(getContext());
	}

	/**
	 * @param context
	 * @return value of Start
	 */
	public final java.util.Date getStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Start.toString());
	}

	/**
	 * Set value of Start
	 * @param start
	 */
	public final void setStart(java.util.Date start)
	{
		setStart(getContext(), start);
	}

	/**
	 * Set value of Start
	 * @param context
	 * @param start
	 */
	public final void setStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date start)
	{
		getMendixObject().setValue(context, MemberNames.Start.toString(), start);
	}

	/**
	 * @return value of End
	 */
	public final java.util.Date getEnd()
	{
		return getEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of End
	 */
	public final java.util.Date getEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.End.toString());
	}

	/**
	 * Set value of End
	 * @param end
	 */
	public final void setEnd(java.util.Date end)
	{
		setEnd(getContext(), end);
	}

	/**
	 * Set value of End
	 * @param context
	 * @param end
	 */
	public final void setEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date end)
	{
		getMendixObject().setValue(context, MemberNames.End.toString(), end);
	}

	/**
	 * @return value of Besonderheiten
	 */
	public final java.lang.String getBesonderheiten()
	{
		return getBesonderheiten(getContext());
	}

	/**
	 * @param context
	 * @return value of Besonderheiten
	 */
	public final java.lang.String getBesonderheiten(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Besonderheiten.toString());
	}

	/**
	 * Set value of Besonderheiten
	 * @param besonderheiten
	 */
	public final void setBesonderheiten(java.lang.String besonderheiten)
	{
		setBesonderheiten(getContext(), besonderheiten);
	}

	/**
	 * Set value of Besonderheiten
	 * @param context
	 * @param besonderheiten
	 */
	public final void setBesonderheiten(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String besonderheiten)
	{
		getMendixObject().setValue(context, MemberNames.Besonderheiten.toString(), besonderheiten);
	}

	/**
	 * @return value of _Spuelen
	 */
	public final java.lang.Boolean get_Spuelen()
	{
		return get_Spuelen(getContext());
	}

	/**
	 * @param context
	 * @return value of _Spuelen
	 */
	public final java.lang.Boolean get_Spuelen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._Spuelen.toString());
	}

	/**
	 * Set value of _Spuelen
	 * @param _spuelen
	 */
	public final void set_Spuelen(java.lang.Boolean _spuelen)
	{
		set_Spuelen(getContext(), _spuelen);
	}

	/**
	 * Set value of _Spuelen
	 * @param context
	 * @param _spuelen
	 */
	public final void set_Spuelen(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _spuelen)
	{
		getMendixObject().setValue(context, MemberNames._Spuelen.toString(), _spuelen);
	}

	/**
	 * @return value of _TVUntersuchung
	 */
	public final java.lang.Boolean get_TVUntersuchung()
	{
		return get_TVUntersuchung(getContext());
	}

	/**
	 * @param context
	 * @return value of _TVUntersuchung
	 */
	public final java.lang.Boolean get_TVUntersuchung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._TVUntersuchung.toString());
	}

	/**
	 * Set value of _TVUntersuchung
	 * @param _tvuntersuchung
	 */
	public final void set_TVUntersuchung(java.lang.Boolean _tvuntersuchung)
	{
		set_TVUntersuchung(getContext(), _tvuntersuchung);
	}

	/**
	 * Set value of _TVUntersuchung
	 * @param context
	 * @param _tvuntersuchung
	 */
	public final void set_TVUntersuchung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _tvuntersuchung)
	{
		getMendixObject().setValue(context, MemberNames._TVUntersuchung.toString(), _tvuntersuchung);
	}

	/**
	 * @return value of _Schachtaufnahme
	 */
	public final java.lang.Boolean get_Schachtaufnahme()
	{
		return get_Schachtaufnahme(getContext());
	}

	/**
	 * @param context
	 * @return value of _Schachtaufnahme
	 */
	public final java.lang.Boolean get_Schachtaufnahme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._Schachtaufnahme.toString());
	}

	/**
	 * Set value of _Schachtaufnahme
	 * @param _schachtaufnahme
	 */
	public final void set_Schachtaufnahme(java.lang.Boolean _schachtaufnahme)
	{
		set_Schachtaufnahme(getContext(), _schachtaufnahme);
	}

	/**
	 * Set value of _Schachtaufnahme
	 * @param context
	 * @param _schachtaufnahme
	 */
	public final void set_Schachtaufnahme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _schachtaufnahme)
	{
		getMendixObject().setValue(context, MemberNames._Schachtaufnahme.toString(), _schachtaufnahme);
	}

	/**
	 * @return value of _Dichtheitspruefung
	 */
	public final java.lang.Boolean get_Dichtheitspruefung()
	{
		return get_Dichtheitspruefung(getContext());
	}

	/**
	 * @param context
	 * @return value of _Dichtheitspruefung
	 */
	public final java.lang.Boolean get_Dichtheitspruefung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._Dichtheitspruefung.toString());
	}

	/**
	 * Set value of _Dichtheitspruefung
	 * @param _dichtheitspruefung
	 */
	public final void set_Dichtheitspruefung(java.lang.Boolean _dichtheitspruefung)
	{
		set_Dichtheitspruefung(getContext(), _dichtheitspruefung);
	}

	/**
	 * Set value of _Dichtheitspruefung
	 * @param context
	 * @param _dichtheitspruefung
	 */
	public final void set_Dichtheitspruefung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _dichtheitspruefung)
	{
		getMendixObject().setValue(context, MemberNames._Dichtheitspruefung.toString(), _dichtheitspruefung);
	}

	/**
	 * @return value of _Nebeln
	 */
	public final java.lang.Boolean get_Nebeln()
	{
		return get_Nebeln(getContext());
	}

	/**
	 * @param context
	 * @return value of _Nebeln
	 */
	public final java.lang.Boolean get_Nebeln(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._Nebeln.toString());
	}

	/**
	 * Set value of _Nebeln
	 * @param _nebeln
	 */
	public final void set_Nebeln(java.lang.Boolean _nebeln)
	{
		set_Nebeln(getContext(), _nebeln);
	}

	/**
	 * Set value of _Nebeln
	 * @param context
	 * @param _nebeln
	 */
	public final void set_Nebeln(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _nebeln)
	{
		getMendixObject().setValue(context, MemberNames._Nebeln.toString(), _nebeln);
	}

	/**
	 * @return value of _LageplanErstellung
	 */
	public final java.lang.Boolean get_LageplanErstellung()
	{
		return get_LageplanErstellung(getContext());
	}

	/**
	 * @param context
	 * @return value of _LageplanErstellung
	 */
	public final java.lang.Boolean get_LageplanErstellung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._LageplanErstellung.toString());
	}

	/**
	 * Set value of _LageplanErstellung
	 * @param _lageplanerstellung
	 */
	public final void set_LageplanErstellung(java.lang.Boolean _lageplanerstellung)
	{
		set_LageplanErstellung(getContext(), _lageplanerstellung);
	}

	/**
	 * Set value of _LageplanErstellung
	 * @param context
	 * @param _lageplanerstellung
	 */
	public final void set_LageplanErstellung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _lageplanerstellung)
	{
		getMendixObject().setValue(context, MemberNames._LageplanErstellung.toString(), _lageplanerstellung);
	}

	/**
	 * @return value of _DokuErstellung
	 */
	public final java.lang.Boolean get_DokuErstellung()
	{
		return get_DokuErstellung(getContext());
	}

	/**
	 * @param context
	 * @return value of _DokuErstellung
	 */
	public final java.lang.Boolean get_DokuErstellung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._DokuErstellung.toString());
	}

	/**
	 * Set value of _DokuErstellung
	 * @param _dokuerstellung
	 */
	public final void set_DokuErstellung(java.lang.Boolean _dokuerstellung)
	{
		set_DokuErstellung(getContext(), _dokuerstellung);
	}

	/**
	 * Set value of _DokuErstellung
	 * @param context
	 * @param _dokuerstellung
	 */
	public final void set_DokuErstellung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _dokuerstellung)
	{
		getMendixObject().setValue(context, MemberNames._DokuErstellung.toString(), _dokuerstellung);
	}

	/**
	 * @return value of _SonstigeArbeiten
	 */
	public final java.lang.Boolean get_SonstigeArbeiten()
	{
		return get_SonstigeArbeiten(getContext());
	}

	/**
	 * @param context
	 * @return value of _SonstigeArbeiten
	 */
	public final java.lang.Boolean get_SonstigeArbeiten(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._SonstigeArbeiten.toString());
	}

	/**
	 * Set value of _SonstigeArbeiten
	 * @param _sonstigearbeiten
	 */
	public final void set_SonstigeArbeiten(java.lang.Boolean _sonstigearbeiten)
	{
		set_SonstigeArbeiten(getContext(), _sonstigearbeiten);
	}

	/**
	 * Set value of _SonstigeArbeiten
	 * @param context
	 * @param _sonstigearbeiten
	 */
	public final void set_SonstigeArbeiten(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _sonstigearbeiten)
	{
		getMendixObject().setValue(context, MemberNames._SonstigeArbeiten.toString(), _sonstigearbeiten);
	}

	/**
	 * @return value of _allDay
	 */
	public final java.lang.Boolean get_allDay()
	{
		return get_allDay(getContext());
	}

	/**
	 * @param context
	 * @return value of _allDay
	 */
	public final java.lang.Boolean get_allDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._allDay.toString());
	}

	/**
	 * Set value of _allDay
	 * @param _allday
	 */
	public final void set_allDay(java.lang.Boolean _allday)
	{
		set_allDay(getContext(), _allday);
	}

	/**
	 * Set value of _allDay
	 * @param context
	 * @param _allday
	 */
	public final void set_allDay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _allday)
	{
		getMendixObject().setValue(context, MemberNames._allDay.toString(), _allday);
	}

	/**
	 * @return value of _wholeDay
	 */
	public final java.lang.Boolean get_wholeDay()
	{
		return get_wholeDay(getContext());
	}

	/**
	 * @param context
	 * @return value of _wholeDay
	 */
	public final java.lang.Boolean get_wholeDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._wholeDay.toString());
	}

	/**
	 * Set value of _wholeDay
	 * @param _wholeday
	 */
	public final void set_wholeDay(java.lang.Boolean _wholeday)
	{
		set_wholeDay(getContext(), _wholeday);
	}

	/**
	 * Set value of _wholeDay
	 * @param context
	 * @param _wholeday
	 */
	public final void set_wholeDay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _wholeday)
	{
		getMendixObject().setValue(context, MemberNames._wholeDay.toString(), _wholeday);
	}

	/**
	 * Get value of EinsatzType
	 * @param einsatztype
	 */
	public final fels.proxies.ENUM_Einsatz_EinsatzType getEinsatzType()
	{
		return getEinsatzType(getContext());
	}

	/**
	 * @param context
	 * @return value of EinsatzType
	 */
	public final fels.proxies.ENUM_Einsatz_EinsatzType getEinsatzType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EinsatzType.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_Einsatz_EinsatzType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EinsatzType
	 * @param einsatztype
	 */
	public final void setEinsatzType(fels.proxies.ENUM_Einsatz_EinsatzType einsatztype)
	{
		setEinsatzType(getContext(), einsatztype);
	}

	/**
	 * Set value of EinsatzType
	 * @param context
	 * @param einsatztype
	 */
	public final void setEinsatzType(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_Einsatz_EinsatzType einsatztype)
	{
		if (einsatztype != null) {
			getMendixObject().setValue(context, MemberNames.EinsatzType.toString(), einsatztype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EinsatzType.toString(), null);
		}
	}

	/**
	 * @return value of CalendarTitel
	 */
	public final java.lang.String getCalendarTitel()
	{
		return getCalendarTitel(getContext());
	}

	/**
	 * @param context
	 * @return value of CalendarTitel
	 */
	public final java.lang.String getCalendarTitel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CalendarTitel.toString());
	}

	/**
	 * Set value of CalendarTitel
	 * @param calendartitel
	 */
	public final void setCalendarTitel(java.lang.String calendartitel)
	{
		setCalendarTitel(getContext(), calendartitel);
	}

	/**
	 * Set value of CalendarTitel
	 * @param context
	 * @param calendartitel
	 */
	public final void setCalendarTitel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String calendartitel)
	{
		getMendixObject().setValue(context, MemberNames.CalendarTitel.toString(), calendartitel);
	}

	/**
	 * Get value of Abwesenheitsgrund
	 * @param abwesenheitsgrund
	 */
	public final fels.proxies.ENUM_Einsatz_Abwesenheitsgrund getAbwesenheitsgrund()
	{
		return getAbwesenheitsgrund(getContext());
	}

	/**
	 * @param context
	 * @return value of Abwesenheitsgrund
	 */
	public final fels.proxies.ENUM_Einsatz_Abwesenheitsgrund getAbwesenheitsgrund(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Abwesenheitsgrund.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_Einsatz_Abwesenheitsgrund.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Abwesenheitsgrund
	 * @param abwesenheitsgrund
	 */
	public final void setAbwesenheitsgrund(fels.proxies.ENUM_Einsatz_Abwesenheitsgrund abwesenheitsgrund)
	{
		setAbwesenheitsgrund(getContext(), abwesenheitsgrund);
	}

	/**
	 * Set value of Abwesenheitsgrund
	 * @param context
	 * @param abwesenheitsgrund
	 */
	public final void setAbwesenheitsgrund(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_Einsatz_Abwesenheitsgrund abwesenheitsgrund)
	{
		if (abwesenheitsgrund != null) {
			getMendixObject().setValue(context, MemberNames.Abwesenheitsgrund.toString(), abwesenheitsgrund.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Abwesenheitsgrund.toString(), null);
		}
	}

	/**
	 * @return value of _Open
	 */
	public final java.lang.Boolean get_Open()
	{
		return get_Open(getContext());
	}

	/**
	 * @param context
	 * @return value of _Open
	 */
	public final java.lang.Boolean get_Open(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._Open.toString());
	}

	/**
	 * Set value of _Open
	 * @param _open
	 */
	public final void set_Open(java.lang.Boolean _open)
	{
		set_Open(getContext(), _open);
	}

	/**
	 * Set value of _Open
	 * @param context
	 * @param _open
	 */
	public final void set_Open(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _open)
	{
		getMendixObject().setValue(context, MemberNames._Open.toString(), _open);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Einsatz_Auftrag
	 */
	public final fels.proxies.Auftrag getEinsatz_Auftrag() throws com.mendix.core.CoreException
	{
		return getEinsatz_Auftrag(getContext());
	}

	/**
	 * @param context
	 * @return value of Einsatz_Auftrag
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Auftrag getEinsatz_Auftrag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Auftrag result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Einsatz_Auftrag.toString());
		if (identifier != null) {
			result = fels.proxies.Auftrag.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Einsatz_Auftrag
	 * @param einsatz_auftrag
	 */
	public final void setEinsatz_Auftrag(fels.proxies.Auftrag einsatz_auftrag)
	{
		setEinsatz_Auftrag(getContext(), einsatz_auftrag);
	}

	/**
	 * Set value of Einsatz_Auftrag
	 * @param context
	 * @param einsatz_auftrag
	 */
	public final void setEinsatz_Auftrag(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Auftrag einsatz_auftrag)
	{
		if (einsatz_auftrag == null) {
			getMendixObject().setValue(context, MemberNames.Einsatz_Auftrag.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Einsatz_Auftrag.toString(), einsatz_auftrag.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Einsatz_Fahrzeug
	 */
	public final java.util.List<fels.proxies.Fahrzeug> getEinsatz_Fahrzeug() throws com.mendix.core.CoreException
	{
		return getEinsatz_Fahrzeug(getContext());
	}

	/**
	 * @param context
	 * @return value of Einsatz_Fahrzeug
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<fels.proxies.Fahrzeug> getEinsatz_Fahrzeug(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<fels.proxies.Fahrzeug> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Einsatz_Fahrzeug.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(fels.proxies.Fahrzeug.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Einsatz_Fahrzeug
	 * @param einsatz_fahrzeug
	 */
	public final void setEinsatz_Fahrzeug(java.util.List<fels.proxies.Fahrzeug> einsatz_fahrzeug)
	{
		setEinsatz_Fahrzeug(getContext(), einsatz_fahrzeug);
	}

	/**
	 * Set value of Einsatz_Fahrzeug
	 * @param context
	 * @param einsatz_fahrzeug
	 */
	public final void setEinsatz_Fahrzeug(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<fels.proxies.Fahrzeug> einsatz_fahrzeug)
	{
		var identifiers = einsatz_fahrzeug
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Einsatz_Fahrzeug.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Einsatz_Mitarbeiter
	 */
	public final java.util.List<fels.proxies.Mitarbeiter> getEinsatz_Mitarbeiter() throws com.mendix.core.CoreException
	{
		return getEinsatz_Mitarbeiter(getContext());
	}

	/**
	 * @param context
	 * @return value of Einsatz_Mitarbeiter
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<fels.proxies.Mitarbeiter> getEinsatz_Mitarbeiter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<fels.proxies.Mitarbeiter> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Einsatz_Mitarbeiter.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(fels.proxies.Mitarbeiter.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Einsatz_Mitarbeiter
	 * @param einsatz_mitarbeiter
	 */
	public final void setEinsatz_Mitarbeiter(java.util.List<fels.proxies.Mitarbeiter> einsatz_mitarbeiter)
	{
		setEinsatz_Mitarbeiter(getContext(), einsatz_mitarbeiter);
	}

	/**
	 * Set value of Einsatz_Mitarbeiter
	 * @param context
	 * @param einsatz_mitarbeiter
	 */
	public final void setEinsatz_Mitarbeiter(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<fels.proxies.Mitarbeiter> einsatz_mitarbeiter)
	{
		var identifiers = einsatz_mitarbeiter
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Einsatz_Mitarbeiter.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Einsatz_Leistung
	 */
	public final java.util.List<fels.proxies.Leistung> getEinsatz_Leistung() throws com.mendix.core.CoreException
	{
		return getEinsatz_Leistung(getContext());
	}

	/**
	 * @param context
	 * @return value of Einsatz_Leistung
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<fels.proxies.Leistung> getEinsatz_Leistung(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<fels.proxies.Leistung> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Einsatz_Leistung.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(fels.proxies.Leistung.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Einsatz_Leistung
	 * @param einsatz_leistung
	 */
	public final void setEinsatz_Leistung(java.util.List<fels.proxies.Leistung> einsatz_leistung)
	{
		setEinsatz_Leistung(getContext(), einsatz_leistung);
	}

	/**
	 * Set value of Einsatz_Leistung
	 * @param context
	 * @param einsatz_leistung
	 */
	public final void setEinsatz_Leistung(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<fels.proxies.Leistung> einsatz_leistung)
	{
		var identifiers = einsatz_leistung
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Einsatz_Leistung.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return einsatzMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Einsatz that = (fels.proxies.Einsatz) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
