// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public enum ENUM_EinsatzHelper_DayPicker
{
	genau_1_Tag(new java.lang.String[][] { new java.lang.String[] { "de_DE", "genau 1 Tag" } }),
	_1_Tag_oder_mehr(new java.lang.String[][] { new java.lang.String[] { "de_DE", "1 Tag oder mehr" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_EinsatzHelper_DayPicker(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "de_DE");
	}

	public java.lang.String getCaption()
	{
		return captions.get("de_DE");
	}
}
