// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public enum ENUM_EinsatzHelper_EinsatzView
{
	Infos(new java.lang.String[][] { new java.lang.String[] { "de_DE", "Infos" } }),
	Leistungsbericht(new java.lang.String[][] { new java.lang.String[] { "de_DE", "Leistungsbericht" } }),
	Tagesbericht(new java.lang.String[][] { new java.lang.String[] { "de_DE", "Tagesbericht" } }),
	Dichtheitspr(new java.lang.String[][] { new java.lang.String[] { "de_DE", "Dichtheitsprüfungen" } }),
	Nebelpr(new java.lang.String[][] { new java.lang.String[] { "de_DE", "Nebelprotokolle" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_EinsatzHelper_EinsatzView(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "de_DE");
	}

	public java.lang.String getCaption()
	{
		return captions.get("de_DE");
	}
}
