// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class ErbrachteLeistung implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject erbrachteLeistungMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.ErbrachteLeistung";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Menge("Menge"),
		Einheit("Einheit"),
		ErbrachteLeistung_Leistung("Fels.ErbrachteLeistung_Leistung"),
		ErbrachteLeistung_Einsatz("Fels.ErbrachteLeistung_Einsatz");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ErbrachteLeistung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ErbrachteLeistung(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject erbrachteLeistungMendixObject)
	{
		if (erbrachteLeistungMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, erbrachteLeistungMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.erbrachteLeistungMendixObject = erbrachteLeistungMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.ErbrachteLeistung initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.ErbrachteLeistung(context, mendixObject);
	}

	public static fels.proxies.ErbrachteLeistung load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.ErbrachteLeistung.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.ErbrachteLeistung> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.ErbrachteLeistung.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Menge
	 */
	public final java.math.BigDecimal getMenge()
	{
		return getMenge(getContext());
	}

	/**
	 * @param context
	 * @return value of Menge
	 */
	public final java.math.BigDecimal getMenge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Menge.toString());
	}

	/**
	 * Set value of Menge
	 * @param menge
	 */
	public final void setMenge(java.math.BigDecimal menge)
	{
		setMenge(getContext(), menge);
	}

	/**
	 * Set value of Menge
	 * @param context
	 * @param menge
	 */
	public final void setMenge(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal menge)
	{
		getMendixObject().setValue(context, MemberNames.Menge.toString(), menge);
	}

	/**
	 * Get value of Einheit
	 * @param einheit
	 */
	public final fels.proxies.ENUM_Position_Einheit getEinheit()
	{
		return getEinheit(getContext());
	}

	/**
	 * @param context
	 * @return value of Einheit
	 */
	public final fels.proxies.ENUM_Position_Einheit getEinheit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Einheit.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_Position_Einheit.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Einheit
	 * @param einheit
	 */
	public final void setEinheit(fels.proxies.ENUM_Position_Einheit einheit)
	{
		setEinheit(getContext(), einheit);
	}

	/**
	 * Set value of Einheit
	 * @param context
	 * @param einheit
	 */
	public final void setEinheit(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_Position_Einheit einheit)
	{
		if (einheit != null) {
			getMendixObject().setValue(context, MemberNames.Einheit.toString(), einheit.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Einheit.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ErbrachteLeistung_Leistung
	 */
	public final fels.proxies.Leistung getErbrachteLeistung_Leistung() throws com.mendix.core.CoreException
	{
		return getErbrachteLeistung_Leistung(getContext());
	}

	/**
	 * @param context
	 * @return value of ErbrachteLeistung_Leistung
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Leistung getErbrachteLeistung_Leistung(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Leistung result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ErbrachteLeistung_Leistung.toString());
		if (identifier != null) {
			result = fels.proxies.Leistung.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ErbrachteLeistung_Leistung
	 * @param erbrachteleistung_leistung
	 */
	public final void setErbrachteLeistung_Leistung(fels.proxies.Leistung erbrachteleistung_leistung)
	{
		setErbrachteLeistung_Leistung(getContext(), erbrachteleistung_leistung);
	}

	/**
	 * Set value of ErbrachteLeistung_Leistung
	 * @param context
	 * @param erbrachteleistung_leistung
	 */
	public final void setErbrachteLeistung_Leistung(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Leistung erbrachteleistung_leistung)
	{
		if (erbrachteleistung_leistung == null) {
			getMendixObject().setValue(context, MemberNames.ErbrachteLeistung_Leistung.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ErbrachteLeistung_Leistung.toString(), erbrachteleistung_leistung.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ErbrachteLeistung_Einsatz
	 */
	public final fels.proxies.Einsatz getErbrachteLeistung_Einsatz() throws com.mendix.core.CoreException
	{
		return getErbrachteLeistung_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of ErbrachteLeistung_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getErbrachteLeistung_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ErbrachteLeistung_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ErbrachteLeistung_Einsatz
	 * @param erbrachteleistung_einsatz
	 */
	public final void setErbrachteLeistung_Einsatz(fels.proxies.Einsatz erbrachteleistung_einsatz)
	{
		setErbrachteLeistung_Einsatz(getContext(), erbrachteleistung_einsatz);
	}

	/**
	 * Set value of ErbrachteLeistung_Einsatz
	 * @param context
	 * @param erbrachteleistung_einsatz
	 */
	public final void setErbrachteLeistung_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz erbrachteleistung_einsatz)
	{
		if (erbrachteleistung_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.ErbrachteLeistung_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ErbrachteLeistung_Einsatz.toString(), erbrachteleistung_einsatz.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return erbrachteLeistungMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.ErbrachteLeistung that = (fels.proxies.ErbrachteLeistung) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
