// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Foto extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Foto";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Kommentar("Kommentar"),
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		TagesberichtFoto_Einsatz("Fels.TagesberichtFoto_Einsatz"),
		Foto_Nebelprotokoll("Fels.Foto_Nebelprotokoll");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Foto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Foto(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fotoMendixObject)
	{
		super(context, fotoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, fotoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Foto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Foto(context, mendixObject);
	}

	public static fels.proxies.Foto load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Foto.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Foto> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Foto.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Kommentar
	 */
	public final java.lang.String getKommentar()
	{
		return getKommentar(getContext());
	}

	/**
	 * @param context
	 * @return value of Kommentar
	 */
	public final java.lang.String getKommentar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kommentar.toString());
	}

	/**
	 * Set value of Kommentar
	 * @param kommentar
	 */
	public final void setKommentar(java.lang.String kommentar)
	{
		setKommentar(getContext(), kommentar);
	}

	/**
	 * Set value of Kommentar
	 * @param context
	 * @param kommentar
	 */
	public final void setKommentar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kommentar)
	{
		getMendixObject().setValue(context, MemberNames.Kommentar.toString(), kommentar);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TagesberichtFoto_Einsatz
	 */
	public final fels.proxies.Einsatz getTagesberichtFoto_Einsatz() throws com.mendix.core.CoreException
	{
		return getTagesberichtFoto_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of TagesberichtFoto_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getTagesberichtFoto_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TagesberichtFoto_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TagesberichtFoto_Einsatz
	 * @param tagesberichtfoto_einsatz
	 */
	public final void setTagesberichtFoto_Einsatz(fels.proxies.Einsatz tagesberichtfoto_einsatz)
	{
		setTagesberichtFoto_Einsatz(getContext(), tagesberichtfoto_einsatz);
	}

	/**
	 * Set value of TagesberichtFoto_Einsatz
	 * @param context
	 * @param tagesberichtfoto_einsatz
	 */
	public final void setTagesberichtFoto_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz tagesberichtfoto_einsatz)
	{
		if (tagesberichtfoto_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.TagesberichtFoto_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TagesberichtFoto_Einsatz.toString(), tagesberichtfoto_einsatz.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Foto_Nebelprotokoll
	 */
	public final fels.proxies.Nebelprotokoll getFoto_Nebelprotokoll() throws com.mendix.core.CoreException
	{
		return getFoto_Nebelprotokoll(getContext());
	}

	/**
	 * @param context
	 * @return value of Foto_Nebelprotokoll
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Nebelprotokoll getFoto_Nebelprotokoll(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Nebelprotokoll result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Foto_Nebelprotokoll.toString());
		if (identifier != null) {
			result = fels.proxies.Nebelprotokoll.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Foto_Nebelprotokoll
	 * @param foto_nebelprotokoll
	 */
	public final void setFoto_Nebelprotokoll(fels.proxies.Nebelprotokoll foto_nebelprotokoll)
	{
		setFoto_Nebelprotokoll(getContext(), foto_nebelprotokoll);
	}

	/**
	 * Set value of Foto_Nebelprotokoll
	 * @param context
	 * @param foto_nebelprotokoll
	 */
	public final void setFoto_Nebelprotokoll(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Nebelprotokoll foto_nebelprotokoll)
	{
		if (foto_nebelprotokoll == null) {
			getMendixObject().setValue(context, MemberNames.Foto_Nebelprotokoll.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Foto_Nebelprotokoll.toString(), foto_nebelprotokoll.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Foto that = (fels.proxies.Foto) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
