// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Leistungsabrechnung implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject leistungsabrechnungMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Leistungsabrechnung";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Eintrag("Eintrag"),
		Leistungsabrechnung_Einsatz("Fels.Leistungsabrechnung_Einsatz"),
		Leistungsabrechnung_Leistungsbereich("Fels.Leistungsabrechnung_Leistungsbereich"),
		Leistungsabrechnung_Position("Fels.Leistungsabrechnung_Position"),
		Leistungsabrechnung_Bemerkung("Fels.Leistungsabrechnung_Bemerkung");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Leistungsabrechnung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Leistungsabrechnung(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject leistungsabrechnungMendixObject)
	{
		if (leistungsabrechnungMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, leistungsabrechnungMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.leistungsabrechnungMendixObject = leistungsabrechnungMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Leistungsabrechnung initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Leistungsabrechnung(context, mendixObject);
	}

	public static fels.proxies.Leistungsabrechnung load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Leistungsabrechnung.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Leistungsabrechnung> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Leistungsabrechnung.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Eintrag
	 */
	public final java.math.BigDecimal getEintrag()
	{
		return getEintrag(getContext());
	}

	/**
	 * @param context
	 * @return value of Eintrag
	 */
	public final java.math.BigDecimal getEintrag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Eintrag.toString());
	}

	/**
	 * Set value of Eintrag
	 * @param eintrag
	 */
	public final void setEintrag(java.math.BigDecimal eintrag)
	{
		setEintrag(getContext(), eintrag);
	}

	/**
	 * Set value of Eintrag
	 * @param context
	 * @param eintrag
	 */
	public final void setEintrag(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal eintrag)
	{
		getMendixObject().setValue(context, MemberNames.Eintrag.toString(), eintrag);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Leistungsabrechnung_Einsatz
	 */
	public final fels.proxies.Einsatz getLeistungsabrechnung_Einsatz() throws com.mendix.core.CoreException
	{
		return getLeistungsabrechnung_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of Leistungsabrechnung_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getLeistungsabrechnung_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Leistungsabrechnung_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Leistungsabrechnung_Einsatz
	 * @param leistungsabrechnung_einsatz
	 */
	public final void setLeistungsabrechnung_Einsatz(fels.proxies.Einsatz leistungsabrechnung_einsatz)
	{
		setLeistungsabrechnung_Einsatz(getContext(), leistungsabrechnung_einsatz);
	}

	/**
	 * Set value of Leistungsabrechnung_Einsatz
	 * @param context
	 * @param leistungsabrechnung_einsatz
	 */
	public final void setLeistungsabrechnung_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz leistungsabrechnung_einsatz)
	{
		if (leistungsabrechnung_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.Leistungsabrechnung_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Leistungsabrechnung_Einsatz.toString(), leistungsabrechnung_einsatz.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Leistungsabrechnung_Leistungsbereich
	 */
	public final fels.proxies.Leistungsbereich getLeistungsabrechnung_Leistungsbereich() throws com.mendix.core.CoreException
	{
		return getLeistungsabrechnung_Leistungsbereich(getContext());
	}

	/**
	 * @param context
	 * @return value of Leistungsabrechnung_Leistungsbereich
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Leistungsbereich getLeistungsabrechnung_Leistungsbereich(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Leistungsbereich result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Leistungsabrechnung_Leistungsbereich.toString());
		if (identifier != null) {
			result = fels.proxies.Leistungsbereich.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Leistungsabrechnung_Leistungsbereich
	 * @param leistungsabrechnung_leistungsbereich
	 */
	public final void setLeistungsabrechnung_Leistungsbereich(fels.proxies.Leistungsbereich leistungsabrechnung_leistungsbereich)
	{
		setLeistungsabrechnung_Leistungsbereich(getContext(), leistungsabrechnung_leistungsbereich);
	}

	/**
	 * Set value of Leistungsabrechnung_Leistungsbereich
	 * @param context
	 * @param leistungsabrechnung_leistungsbereich
	 */
	public final void setLeistungsabrechnung_Leistungsbereich(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Leistungsbereich leistungsabrechnung_leistungsbereich)
	{
		if (leistungsabrechnung_leistungsbereich == null) {
			getMendixObject().setValue(context, MemberNames.Leistungsabrechnung_Leistungsbereich.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Leistungsabrechnung_Leistungsbereich.toString(), leistungsabrechnung_leistungsbereich.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Leistungsabrechnung_Position
	 */
	public final fels.proxies.Position getLeistungsabrechnung_Position() throws com.mendix.core.CoreException
	{
		return getLeistungsabrechnung_Position(getContext());
	}

	/**
	 * @param context
	 * @return value of Leistungsabrechnung_Position
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Position getLeistungsabrechnung_Position(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Position result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Leistungsabrechnung_Position.toString());
		if (identifier != null) {
			result = fels.proxies.Position.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Leistungsabrechnung_Position
	 * @param leistungsabrechnung_position
	 */
	public final void setLeistungsabrechnung_Position(fels.proxies.Position leistungsabrechnung_position)
	{
		setLeistungsabrechnung_Position(getContext(), leistungsabrechnung_position);
	}

	/**
	 * Set value of Leistungsabrechnung_Position
	 * @param context
	 * @param leistungsabrechnung_position
	 */
	public final void setLeistungsabrechnung_Position(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Position leistungsabrechnung_position)
	{
		if (leistungsabrechnung_position == null) {
			getMendixObject().setValue(context, MemberNames.Leistungsabrechnung_Position.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Leistungsabrechnung_Position.toString(), leistungsabrechnung_position.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Leistungsabrechnung_Bemerkung
	 */
	public final fels.proxies.Bemerkung getLeistungsabrechnung_Bemerkung() throws com.mendix.core.CoreException
	{
		return getLeistungsabrechnung_Bemerkung(getContext());
	}

	/**
	 * @param context
	 * @return value of Leistungsabrechnung_Bemerkung
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Bemerkung getLeistungsabrechnung_Bemerkung(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Bemerkung result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Leistungsabrechnung_Bemerkung.toString());
		if (identifier != null) {
			result = fels.proxies.Bemerkung.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Leistungsabrechnung_Bemerkung
	 * @param leistungsabrechnung_bemerkung
	 */
	public final void setLeistungsabrechnung_Bemerkung(fels.proxies.Bemerkung leistungsabrechnung_bemerkung)
	{
		setLeistungsabrechnung_Bemerkung(getContext(), leistungsabrechnung_bemerkung);
	}

	/**
	 * Set value of Leistungsabrechnung_Bemerkung
	 * @param context
	 * @param leistungsabrechnung_bemerkung
	 */
	public final void setLeistungsabrechnung_Bemerkung(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Bemerkung leistungsabrechnung_bemerkung)
	{
		if (leistungsabrechnung_bemerkung == null) {
			getMendixObject().setValue(context, MemberNames.Leistungsabrechnung_Bemerkung.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Leistungsabrechnung_Bemerkung.toString(), leistungsabrechnung_bemerkung.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return leistungsabrechnungMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Leistungsabrechnung that = (fels.proxies.Leistungsabrechnung) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
