// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class LeistungHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject leistungHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.LeistungHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Beschreibung("Beschreibung"),
		_relevant("_relevant"),
		LeistungHelper_Leistung("Fels.LeistungHelper_Leistung"),
		LeistungHelper_Einsatz("Fels.LeistungHelper_Einsatz");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LeistungHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LeistungHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject leistungHelperMendixObject)
	{
		if (leistungHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, leistungHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.leistungHelperMendixObject = leistungHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.LeistungHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.LeistungHelper(context, mendixObject);
	}

	public static fels.proxies.LeistungHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.LeistungHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Beschreibung
	 */
	public final java.lang.String getBeschreibung()
	{
		return getBeschreibung(getContext());
	}

	/**
	 * @param context
	 * @return value of Beschreibung
	 */
	public final java.lang.String getBeschreibung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Beschreibung.toString());
	}

	/**
	 * Set value of Beschreibung
	 * @param beschreibung
	 */
	public final void setBeschreibung(java.lang.String beschreibung)
	{
		setBeschreibung(getContext(), beschreibung);
	}

	/**
	 * Set value of Beschreibung
	 * @param context
	 * @param beschreibung
	 */
	public final void setBeschreibung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String beschreibung)
	{
		getMendixObject().setValue(context, MemberNames.Beschreibung.toString(), beschreibung);
	}

	/**
	 * @return value of _relevant
	 */
	public final java.lang.Boolean get_relevant()
	{
		return get_relevant(getContext());
	}

	/**
	 * @param context
	 * @return value of _relevant
	 */
	public final java.lang.Boolean get_relevant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._relevant.toString());
	}

	/**
	 * Set value of _relevant
	 * @param _relevant
	 */
	public final void set_relevant(java.lang.Boolean _relevant)
	{
		set_relevant(getContext(), _relevant);
	}

	/**
	 * Set value of _relevant
	 * @param context
	 * @param _relevant
	 */
	public final void set_relevant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _relevant)
	{
		getMendixObject().setValue(context, MemberNames._relevant.toString(), _relevant);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LeistungHelper_Leistung
	 */
	public final fels.proxies.Leistung getLeistungHelper_Leistung() throws com.mendix.core.CoreException
	{
		return getLeistungHelper_Leistung(getContext());
	}

	/**
	 * @param context
	 * @return value of LeistungHelper_Leistung
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Leistung getLeistungHelper_Leistung(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Leistung result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LeistungHelper_Leistung.toString());
		if (identifier != null) {
			result = fels.proxies.Leistung.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LeistungHelper_Leistung
	 * @param leistunghelper_leistung
	 */
	public final void setLeistungHelper_Leistung(fels.proxies.Leistung leistunghelper_leistung)
	{
		setLeistungHelper_Leistung(getContext(), leistunghelper_leistung);
	}

	/**
	 * Set value of LeistungHelper_Leistung
	 * @param context
	 * @param leistunghelper_leistung
	 */
	public final void setLeistungHelper_Leistung(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Leistung leistunghelper_leistung)
	{
		if (leistunghelper_leistung == null) {
			getMendixObject().setValue(context, MemberNames.LeistungHelper_Leistung.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LeistungHelper_Leistung.toString(), leistunghelper_leistung.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LeistungHelper_Einsatz
	 */
	public final fels.proxies.Einsatz getLeistungHelper_Einsatz() throws com.mendix.core.CoreException
	{
		return getLeistungHelper_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of LeistungHelper_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getLeistungHelper_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LeistungHelper_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LeistungHelper_Einsatz
	 * @param leistunghelper_einsatz
	 */
	public final void setLeistungHelper_Einsatz(fels.proxies.Einsatz leistunghelper_einsatz)
	{
		setLeistungHelper_Einsatz(getContext(), leistunghelper_einsatz);
	}

	/**
	 * Set value of LeistungHelper_Einsatz
	 * @param context
	 * @param leistunghelper_einsatz
	 */
	public final void setLeistungHelper_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz leistunghelper_einsatz)
	{
		if (leistunghelper_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.LeistungHelper_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LeistungHelper_Einsatz.toString(), leistunghelper_einsatz.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return leistungHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.LeistungHelper that = (fels.proxies.LeistungHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
