// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class LeistungsbereichBuilder implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject leistungsbereichBuilderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.LeistungsbereichBuilder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Day("Day"),
		Nummer("Nummer"),
		Beschreibung("Beschreibung"),
		Einheit("Einheit"),
		Preis("Preis"),
		Eintrag1("Eintrag1"),
		Eintrag2("Eintrag2"),
		Farbe("Farbe"),
		_WithEuro("_WithEuro"),
		_ShowNothing("_ShowNothing"),
		LeistungsbereichBuilder_Einsatz("Fels.LeistungsbereichBuilder_Einsatz");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LeistungsbereichBuilder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LeistungsbereichBuilder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject leistungsbereichBuilderMendixObject)
	{
		if (leistungsbereichBuilderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, leistungsbereichBuilderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.leistungsbereichBuilderMendixObject = leistungsbereichBuilderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.LeistungsbereichBuilder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.LeistungsbereichBuilder(context, mendixObject);
	}

	public static fels.proxies.LeistungsbereichBuilder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.LeistungsbereichBuilder.initialize(context, mendixObject);
	}

	/**
	 * @return value of Day
	 */
	public final java.util.Date getDay()
	{
		return getDay(getContext());
	}

	/**
	 * @param context
	 * @return value of Day
	 */
	public final java.util.Date getDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Day.toString());
	}

	/**
	 * Set value of Day
	 * @param day
	 */
	public final void setDay(java.util.Date day)
	{
		setDay(getContext(), day);
	}

	/**
	 * Set value of Day
	 * @param context
	 * @param day
	 */
	public final void setDay(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date day)
	{
		getMendixObject().setValue(context, MemberNames.Day.toString(), day);
	}

	/**
	 * @return value of Nummer
	 */
	public final java.lang.String getNummer()
	{
		return getNummer(getContext());
	}

	/**
	 * @param context
	 * @return value of Nummer
	 */
	public final java.lang.String getNummer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nummer.toString());
	}

	/**
	 * Set value of Nummer
	 * @param nummer
	 */
	public final void setNummer(java.lang.String nummer)
	{
		setNummer(getContext(), nummer);
	}

	/**
	 * Set value of Nummer
	 * @param context
	 * @param nummer
	 */
	public final void setNummer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nummer)
	{
		getMendixObject().setValue(context, MemberNames.Nummer.toString(), nummer);
	}

	/**
	 * @return value of Beschreibung
	 */
	public final java.lang.String getBeschreibung()
	{
		return getBeschreibung(getContext());
	}

	/**
	 * @param context
	 * @return value of Beschreibung
	 */
	public final java.lang.String getBeschreibung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Beschreibung.toString());
	}

	/**
	 * Set value of Beschreibung
	 * @param beschreibung
	 */
	public final void setBeschreibung(java.lang.String beschreibung)
	{
		setBeschreibung(getContext(), beschreibung);
	}

	/**
	 * Set value of Beschreibung
	 * @param context
	 * @param beschreibung
	 */
	public final void setBeschreibung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String beschreibung)
	{
		getMendixObject().setValue(context, MemberNames.Beschreibung.toString(), beschreibung);
	}

	/**
	 * Get value of Einheit
	 * @param einheit
	 */
	public final fels.proxies.ENUM_Position_Einheit getEinheit()
	{
		return getEinheit(getContext());
	}

	/**
	 * @param context
	 * @return value of Einheit
	 */
	public final fels.proxies.ENUM_Position_Einheit getEinheit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Einheit.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_Position_Einheit.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Einheit
	 * @param einheit
	 */
	public final void setEinheit(fels.proxies.ENUM_Position_Einheit einheit)
	{
		setEinheit(getContext(), einheit);
	}

	/**
	 * Set value of Einheit
	 * @param context
	 * @param einheit
	 */
	public final void setEinheit(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_Position_Einheit einheit)
	{
		if (einheit != null) {
			getMendixObject().setValue(context, MemberNames.Einheit.toString(), einheit.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Einheit.toString(), null);
		}
	}

	/**
	 * @return value of Preis
	 */
	public final java.math.BigDecimal getPreis()
	{
		return getPreis(getContext());
	}

	/**
	 * @param context
	 * @return value of Preis
	 */
	public final java.math.BigDecimal getPreis(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Preis.toString());
	}

	/**
	 * Set value of Preis
	 * @param preis
	 */
	public final void setPreis(java.math.BigDecimal preis)
	{
		setPreis(getContext(), preis);
	}

	/**
	 * Set value of Preis
	 * @param context
	 * @param preis
	 */
	public final void setPreis(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal preis)
	{
		getMendixObject().setValue(context, MemberNames.Preis.toString(), preis);
	}

	/**
	 * @return value of Eintrag1
	 */
	public final java.math.BigDecimal getEintrag1()
	{
		return getEintrag1(getContext());
	}

	/**
	 * @param context
	 * @return value of Eintrag1
	 */
	public final java.math.BigDecimal getEintrag1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Eintrag1.toString());
	}

	/**
	 * Set value of Eintrag1
	 * @param eintrag1
	 */
	public final void setEintrag1(java.math.BigDecimal eintrag1)
	{
		setEintrag1(getContext(), eintrag1);
	}

	/**
	 * Set value of Eintrag1
	 * @param context
	 * @param eintrag1
	 */
	public final void setEintrag1(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal eintrag1)
	{
		getMendixObject().setValue(context, MemberNames.Eintrag1.toString(), eintrag1);
	}

	/**
	 * @return value of Eintrag2
	 */
	public final java.math.BigDecimal getEintrag2()
	{
		return getEintrag2(getContext());
	}

	/**
	 * @param context
	 * @return value of Eintrag2
	 */
	public final java.math.BigDecimal getEintrag2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Eintrag2.toString());
	}

	/**
	 * Set value of Eintrag2
	 * @param eintrag2
	 */
	public final void setEintrag2(java.math.BigDecimal eintrag2)
	{
		setEintrag2(getContext(), eintrag2);
	}

	/**
	 * Set value of Eintrag2
	 * @param context
	 * @param eintrag2
	 */
	public final void setEintrag2(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal eintrag2)
	{
		getMendixObject().setValue(context, MemberNames.Eintrag2.toString(), eintrag2);
	}

	/**
	 * @return value of Farbe
	 */
	public final java.lang.String getFarbe()
	{
		return getFarbe(getContext());
	}

	/**
	 * @param context
	 * @return value of Farbe
	 */
	public final java.lang.String getFarbe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Farbe.toString());
	}

	/**
	 * Set value of Farbe
	 * @param farbe
	 */
	public final void setFarbe(java.lang.String farbe)
	{
		setFarbe(getContext(), farbe);
	}

	/**
	 * Set value of Farbe
	 * @param context
	 * @param farbe
	 */
	public final void setFarbe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String farbe)
	{
		getMendixObject().setValue(context, MemberNames.Farbe.toString(), farbe);
	}

	/**
	 * @return value of _WithEuro
	 */
	public final java.lang.Boolean get_WithEuro()
	{
		return get_WithEuro(getContext());
	}

	/**
	 * @param context
	 * @return value of _WithEuro
	 */
	public final java.lang.Boolean get_WithEuro(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._WithEuro.toString());
	}

	/**
	 * Set value of _WithEuro
	 * @param _witheuro
	 */
	public final void set_WithEuro(java.lang.Boolean _witheuro)
	{
		set_WithEuro(getContext(), _witheuro);
	}

	/**
	 * Set value of _WithEuro
	 * @param context
	 * @param _witheuro
	 */
	public final void set_WithEuro(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _witheuro)
	{
		getMendixObject().setValue(context, MemberNames._WithEuro.toString(), _witheuro);
	}

	/**
	 * @return value of _ShowNothing
	 */
	public final java.lang.Boolean get_ShowNothing()
	{
		return get_ShowNothing(getContext());
	}

	/**
	 * @param context
	 * @return value of _ShowNothing
	 */
	public final java.lang.Boolean get_ShowNothing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._ShowNothing.toString());
	}

	/**
	 * Set value of _ShowNothing
	 * @param _shownothing
	 */
	public final void set_ShowNothing(java.lang.Boolean _shownothing)
	{
		set_ShowNothing(getContext(), _shownothing);
	}

	/**
	 * Set value of _ShowNothing
	 * @param context
	 * @param _shownothing
	 */
	public final void set_ShowNothing(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _shownothing)
	{
		getMendixObject().setValue(context, MemberNames._ShowNothing.toString(), _shownothing);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LeistungsbereichBuilder_Einsatz
	 */
	public final fels.proxies.Einsatz getLeistungsbereichBuilder_Einsatz() throws com.mendix.core.CoreException
	{
		return getLeistungsbereichBuilder_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of LeistungsbereichBuilder_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getLeistungsbereichBuilder_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LeistungsbereichBuilder_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LeistungsbereichBuilder_Einsatz
	 * @param leistungsbereichbuilder_einsatz
	 */
	public final void setLeistungsbereichBuilder_Einsatz(fels.proxies.Einsatz leistungsbereichbuilder_einsatz)
	{
		setLeistungsbereichBuilder_Einsatz(getContext(), leistungsbereichbuilder_einsatz);
	}

	/**
	 * Set value of LeistungsbereichBuilder_Einsatz
	 * @param context
	 * @param leistungsbereichbuilder_einsatz
	 */
	public final void setLeistungsbereichBuilder_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz leistungsbereichbuilder_einsatz)
	{
		if (leistungsbereichbuilder_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.LeistungsbereichBuilder_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LeistungsbereichBuilder_Einsatz.toString(), leistungsbereichbuilder_einsatz.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return leistungsbereichBuilderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.LeistungsbereichBuilder that = (fels.proxies.LeistungsbereichBuilder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
