// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Leistungsbereich implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject leistungsbereichMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Leistungsbereich";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Leistungsbereich_Auftraggeber("Fels.Leistungsbereich_Auftraggeber");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Leistungsbereich(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Leistungsbereich(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject leistungsbereichMendixObject)
	{
		if (leistungsbereichMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, leistungsbereichMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.leistungsbereichMendixObject = leistungsbereichMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Leistungsbereich initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Leistungsbereich(context, mendixObject);
	}

	public static fels.proxies.Leistungsbereich load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Leistungsbereich.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Leistungsbereich> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Leistungsbereich.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Leistungsbereich_Auftraggeber
	 */
	public final fels.proxies.Auftraggeber getLeistungsbereich_Auftraggeber() throws com.mendix.core.CoreException
	{
		return getLeistungsbereich_Auftraggeber(getContext());
	}

	/**
	 * @param context
	 * @return value of Leistungsbereich_Auftraggeber
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Auftraggeber getLeistungsbereich_Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Auftraggeber result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Leistungsbereich_Auftraggeber.toString());
		if (identifier != null) {
			result = fels.proxies.Auftraggeber.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Leistungsbereich_Auftraggeber
	 * @param leistungsbereich_auftraggeber
	 */
	public final void setLeistungsbereich_Auftraggeber(fels.proxies.Auftraggeber leistungsbereich_auftraggeber)
	{
		setLeistungsbereich_Auftraggeber(getContext(), leistungsbereich_auftraggeber);
	}

	/**
	 * Set value of Leistungsbereich_Auftraggeber
	 * @param context
	 * @param leistungsbereich_auftraggeber
	 */
	public final void setLeistungsbereich_Auftraggeber(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Auftraggeber leistungsbereich_auftraggeber)
	{
		if (leistungsbereich_auftraggeber == null) {
			getMendixObject().setValue(context, MemberNames.Leistungsbereich_Auftraggeber.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Leistungsbereich_Auftraggeber.toString(), leistungsbereich_auftraggeber.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return leistungsbereichMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Leistungsbereich that = (fels.proxies.Leistungsbereich) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
