// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Leistung implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject leistungMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Leistung";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Beschreibung("Beschreibung"),
		Einheit("Einheit"),
		_standard("_standard");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Leistung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Leistung(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject leistungMendixObject)
	{
		if (leistungMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, leistungMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.leistungMendixObject = leistungMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Leistung initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Leistung(context, mendixObject);
	}

	public static fels.proxies.Leistung load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Leistung.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Leistung> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Leistung.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Beschreibung
	 */
	public final java.lang.String getBeschreibung()
	{
		return getBeschreibung(getContext());
	}

	/**
	 * @param context
	 * @return value of Beschreibung
	 */
	public final java.lang.String getBeschreibung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Beschreibung.toString());
	}

	/**
	 * Set value of Beschreibung
	 * @param beschreibung
	 */
	public final void setBeschreibung(java.lang.String beschreibung)
	{
		setBeschreibung(getContext(), beschreibung);
	}

	/**
	 * Set value of Beschreibung
	 * @param context
	 * @param beschreibung
	 */
	public final void setBeschreibung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String beschreibung)
	{
		getMendixObject().setValue(context, MemberNames.Beschreibung.toString(), beschreibung);
	}

	/**
	 * Get value of Einheit
	 * @param einheit
	 */
	public final fels.proxies.ENUM_Position_Einheit getEinheit()
	{
		return getEinheit(getContext());
	}

	/**
	 * @param context
	 * @return value of Einheit
	 */
	public final fels.proxies.ENUM_Position_Einheit getEinheit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Einheit.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_Position_Einheit.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Einheit
	 * @param einheit
	 */
	public final void setEinheit(fels.proxies.ENUM_Position_Einheit einheit)
	{
		setEinheit(getContext(), einheit);
	}

	/**
	 * Set value of Einheit
	 * @param context
	 * @param einheit
	 */
	public final void setEinheit(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_Position_Einheit einheit)
	{
		if (einheit != null) {
			getMendixObject().setValue(context, MemberNames.Einheit.toString(), einheit.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Einheit.toString(), null);
		}
	}

	/**
	 * @return value of _standard
	 */
	public final java.lang.Boolean get_standard()
	{
		return get_standard(getContext());
	}

	/**
	 * @param context
	 * @return value of _standard
	 */
	public final java.lang.Boolean get_standard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._standard.toString());
	}

	/**
	 * Set value of _standard
	 * @param _standard
	 */
	public final void set_standard(java.lang.Boolean _standard)
	{
		set_standard(getContext(), _standard);
	}

	/**
	 * Set value of _standard
	 * @param context
	 * @param _standard
	 */
	public final void set_standard(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _standard)
	{
		getMendixObject().setValue(context, MemberNames._standard.toString(), _standard);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return leistungMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Leistung that = (fels.proxies.Leistung) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
