// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Nebelprotokoll implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nebelprotokollMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Nebelprotokoll";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Kommentar("Kommentar"),
		Ort("Ort"),
		Strasse("Strasse"),
		Hausnummber("Hausnummber"),
		Nebelprotokoll_Einsatz("Fels.Nebelprotokoll_Einsatz");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Nebelprotokoll(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Nebelprotokoll(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nebelprotokollMendixObject)
	{
		if (nebelprotokollMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, nebelprotokollMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.nebelprotokollMendixObject = nebelprotokollMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Nebelprotokoll initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Nebelprotokoll(context, mendixObject);
	}

	public static fels.proxies.Nebelprotokoll load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Nebelprotokoll.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Nebelprotokoll> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Nebelprotokoll.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Kommentar
	 */
	public final java.lang.String getKommentar()
	{
		return getKommentar(getContext());
	}

	/**
	 * @param context
	 * @return value of Kommentar
	 */
	public final java.lang.String getKommentar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kommentar.toString());
	}

	/**
	 * Set value of Kommentar
	 * @param kommentar
	 */
	public final void setKommentar(java.lang.String kommentar)
	{
		setKommentar(getContext(), kommentar);
	}

	/**
	 * Set value of Kommentar
	 * @param context
	 * @param kommentar
	 */
	public final void setKommentar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kommentar)
	{
		getMendixObject().setValue(context, MemberNames.Kommentar.toString(), kommentar);
	}

	/**
	 * @return value of Ort
	 */
	public final java.lang.String getOrt()
	{
		return getOrt(getContext());
	}

	/**
	 * @param context
	 * @return value of Ort
	 */
	public final java.lang.String getOrt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ort.toString());
	}

	/**
	 * Set value of Ort
	 * @param ort
	 */
	public final void setOrt(java.lang.String ort)
	{
		setOrt(getContext(), ort);
	}

	/**
	 * Set value of Ort
	 * @param context
	 * @param ort
	 */
	public final void setOrt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ort)
	{
		getMendixObject().setValue(context, MemberNames.Ort.toString(), ort);
	}

	/**
	 * @return value of Strasse
	 */
	public final java.lang.String getStrasse()
	{
		return getStrasse(getContext());
	}

	/**
	 * @param context
	 * @return value of Strasse
	 */
	public final java.lang.String getStrasse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Strasse.toString());
	}

	/**
	 * Set value of Strasse
	 * @param strasse
	 */
	public final void setStrasse(java.lang.String strasse)
	{
		setStrasse(getContext(), strasse);
	}

	/**
	 * Set value of Strasse
	 * @param context
	 * @param strasse
	 */
	public final void setStrasse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String strasse)
	{
		getMendixObject().setValue(context, MemberNames.Strasse.toString(), strasse);
	}

	/**
	 * @return value of Hausnummber
	 */
	public final java.lang.String getHausnummber()
	{
		return getHausnummber(getContext());
	}

	/**
	 * @param context
	 * @return value of Hausnummber
	 */
	public final java.lang.String getHausnummber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hausnummber.toString());
	}

	/**
	 * Set value of Hausnummber
	 * @param hausnummber
	 */
	public final void setHausnummber(java.lang.String hausnummber)
	{
		setHausnummber(getContext(), hausnummber);
	}

	/**
	 * Set value of Hausnummber
	 * @param context
	 * @param hausnummber
	 */
	public final void setHausnummber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hausnummber)
	{
		getMendixObject().setValue(context, MemberNames.Hausnummber.toString(), hausnummber);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Nebelprotokoll_Einsatz
	 */
	public final fels.proxies.Einsatz getNebelprotokoll_Einsatz() throws com.mendix.core.CoreException
	{
		return getNebelprotokoll_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of Nebelprotokoll_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getNebelprotokoll_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Nebelprotokoll_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Nebelprotokoll_Einsatz
	 * @param nebelprotokoll_einsatz
	 */
	public final void setNebelprotokoll_Einsatz(fels.proxies.Einsatz nebelprotokoll_einsatz)
	{
		setNebelprotokoll_Einsatz(getContext(), nebelprotokoll_einsatz);
	}

	/**
	 * Set value of Nebelprotokoll_Einsatz
	 * @param context
	 * @param nebelprotokoll_einsatz
	 */
	public final void setNebelprotokoll_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz nebelprotokoll_einsatz)
	{
		if (nebelprotokoll_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.Nebelprotokoll_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Nebelprotokoll_Einsatz.toString(), nebelprotokoll_einsatz.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nebelprotokollMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Nebelprotokoll that = (fels.proxies.Nebelprotokoll) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
