// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Schacht implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject schachtMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Schacht";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Lagebeschreibung("Lagebeschreibung"),
		Bezeichnung("Bezeichnung"),
		Kommentar("Kommentar"),
		Tiefe("Tiefe"),
		Form("Form"),
		Durchmesser("Durchmesser"),
		Laenge("Laenge"),
		Breite("Breite"),
		Schachtwand("Schachtwand"),
		Schachtsole("Schachtsole"),
		MaxVerlust("MaxVerlust"),
		IstVerlust("IstVerlust"),
		_bestanden("_bestanden"),
		Score("Score"),
		Uhrzeit("Uhrzeit"),
		Dauer("Dauer"),
		Schacht_Einsatz("Fels.Schacht_Einsatz"),
		Schacht_Pruefer("Fels.Schacht_Pruefer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Schacht(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Schacht(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject schachtMendixObject)
	{
		if (schachtMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, schachtMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.schachtMendixObject = schachtMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Schacht initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Schacht(context, mendixObject);
	}

	public static fels.proxies.Schacht load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Schacht.initialize(context, mendixObject);
	}

	public static java.util.List<fels.proxies.Schacht> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> fels.proxies.Schacht.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Lagebeschreibung
	 */
	public final java.lang.String getLagebeschreibung()
	{
		return getLagebeschreibung(getContext());
	}

	/**
	 * @param context
	 * @return value of Lagebeschreibung
	 */
	public final java.lang.String getLagebeschreibung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Lagebeschreibung.toString());
	}

	/**
	 * Set value of Lagebeschreibung
	 * @param lagebeschreibung
	 */
	public final void setLagebeschreibung(java.lang.String lagebeschreibung)
	{
		setLagebeschreibung(getContext(), lagebeschreibung);
	}

	/**
	 * Set value of Lagebeschreibung
	 * @param context
	 * @param lagebeschreibung
	 */
	public final void setLagebeschreibung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lagebeschreibung)
	{
		getMendixObject().setValue(context, MemberNames.Lagebeschreibung.toString(), lagebeschreibung);
	}

	/**
	 * @return value of Bezeichnung
	 */
	public final java.lang.String getBezeichnung()
	{
		return getBezeichnung(getContext());
	}

	/**
	 * @param context
	 * @return value of Bezeichnung
	 */
	public final java.lang.String getBezeichnung(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Bezeichnung.toString());
	}

	/**
	 * Set value of Bezeichnung
	 * @param bezeichnung
	 */
	public final void setBezeichnung(java.lang.String bezeichnung)
	{
		setBezeichnung(getContext(), bezeichnung);
	}

	/**
	 * Set value of Bezeichnung
	 * @param context
	 * @param bezeichnung
	 */
	public final void setBezeichnung(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bezeichnung)
	{
		getMendixObject().setValue(context, MemberNames.Bezeichnung.toString(), bezeichnung);
	}

	/**
	 * @return value of Kommentar
	 */
	public final java.lang.String getKommentar()
	{
		return getKommentar(getContext());
	}

	/**
	 * @param context
	 * @return value of Kommentar
	 */
	public final java.lang.String getKommentar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kommentar.toString());
	}

	/**
	 * Set value of Kommentar
	 * @param kommentar
	 */
	public final void setKommentar(java.lang.String kommentar)
	{
		setKommentar(getContext(), kommentar);
	}

	/**
	 * Set value of Kommentar
	 * @param context
	 * @param kommentar
	 */
	public final void setKommentar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kommentar)
	{
		getMendixObject().setValue(context, MemberNames.Kommentar.toString(), kommentar);
	}

	/**
	 * @return value of Tiefe
	 */
	public final java.math.BigDecimal getTiefe()
	{
		return getTiefe(getContext());
	}

	/**
	 * @param context
	 * @return value of Tiefe
	 */
	public final java.math.BigDecimal getTiefe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Tiefe.toString());
	}

	/**
	 * Set value of Tiefe
	 * @param tiefe
	 */
	public final void setTiefe(java.math.BigDecimal tiefe)
	{
		setTiefe(getContext(), tiefe);
	}

	/**
	 * Set value of Tiefe
	 * @param context
	 * @param tiefe
	 */
	public final void setTiefe(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal tiefe)
	{
		getMendixObject().setValue(context, MemberNames.Tiefe.toString(), tiefe);
	}

	/**
	 * Get value of Form
	 * @param form
	 */
	public final fels.proxies.ENUM_Schacht_Form getForm()
	{
		return getForm(getContext());
	}

	/**
	 * @param context
	 * @return value of Form
	 */
	public final fels.proxies.ENUM_Schacht_Form getForm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Form.toString());
		if (obj == null) {
			return null;
		}
		return fels.proxies.ENUM_Schacht_Form.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Form
	 * @param form
	 */
	public final void setForm(fels.proxies.ENUM_Schacht_Form form)
	{
		setForm(getContext(), form);
	}

	/**
	 * Set value of Form
	 * @param context
	 * @param form
	 */
	public final void setForm(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.ENUM_Schacht_Form form)
	{
		if (form != null) {
			getMendixObject().setValue(context, MemberNames.Form.toString(), form.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Form.toString(), null);
		}
	}

	/**
	 * @return value of Durchmesser
	 */
	public final java.math.BigDecimal getDurchmesser()
	{
		return getDurchmesser(getContext());
	}

	/**
	 * @param context
	 * @return value of Durchmesser
	 */
	public final java.math.BigDecimal getDurchmesser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Durchmesser.toString());
	}

	/**
	 * Set value of Durchmesser
	 * @param durchmesser
	 */
	public final void setDurchmesser(java.math.BigDecimal durchmesser)
	{
		setDurchmesser(getContext(), durchmesser);
	}

	/**
	 * Set value of Durchmesser
	 * @param context
	 * @param durchmesser
	 */
	public final void setDurchmesser(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal durchmesser)
	{
		getMendixObject().setValue(context, MemberNames.Durchmesser.toString(), durchmesser);
	}

	/**
	 * @return value of Laenge
	 */
	public final java.math.BigDecimal getLaenge()
	{
		return getLaenge(getContext());
	}

	/**
	 * @param context
	 * @return value of Laenge
	 */
	public final java.math.BigDecimal getLaenge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Laenge.toString());
	}

	/**
	 * Set value of Laenge
	 * @param laenge
	 */
	public final void setLaenge(java.math.BigDecimal laenge)
	{
		setLaenge(getContext(), laenge);
	}

	/**
	 * Set value of Laenge
	 * @param context
	 * @param laenge
	 */
	public final void setLaenge(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal laenge)
	{
		getMendixObject().setValue(context, MemberNames.Laenge.toString(), laenge);
	}

	/**
	 * @return value of Breite
	 */
	public final java.math.BigDecimal getBreite()
	{
		return getBreite(getContext());
	}

	/**
	 * @param context
	 * @return value of Breite
	 */
	public final java.math.BigDecimal getBreite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Breite.toString());
	}

	/**
	 * Set value of Breite
	 * @param breite
	 */
	public final void setBreite(java.math.BigDecimal breite)
	{
		setBreite(getContext(), breite);
	}

	/**
	 * Set value of Breite
	 * @param context
	 * @param breite
	 */
	public final void setBreite(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal breite)
	{
		getMendixObject().setValue(context, MemberNames.Breite.toString(), breite);
	}

	/**
	 * @return value of Schachtwand
	 */
	public final java.math.BigDecimal getSchachtwand()
	{
		return getSchachtwand(getContext());
	}

	/**
	 * @param context
	 * @return value of Schachtwand
	 */
	public final java.math.BigDecimal getSchachtwand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Schachtwand.toString());
	}

	/**
	 * Set value of Schachtwand
	 * @param schachtwand
	 */
	public final void setSchachtwand(java.math.BigDecimal schachtwand)
	{
		setSchachtwand(getContext(), schachtwand);
	}

	/**
	 * Set value of Schachtwand
	 * @param context
	 * @param schachtwand
	 */
	public final void setSchachtwand(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal schachtwand)
	{
		getMendixObject().setValue(context, MemberNames.Schachtwand.toString(), schachtwand);
	}

	/**
	 * @return value of Schachtsole
	 */
	public final java.math.BigDecimal getSchachtsole()
	{
		return getSchachtsole(getContext());
	}

	/**
	 * @param context
	 * @return value of Schachtsole
	 */
	public final java.math.BigDecimal getSchachtsole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Schachtsole.toString());
	}

	/**
	 * Set value of Schachtsole
	 * @param schachtsole
	 */
	public final void setSchachtsole(java.math.BigDecimal schachtsole)
	{
		setSchachtsole(getContext(), schachtsole);
	}

	/**
	 * Set value of Schachtsole
	 * @param context
	 * @param schachtsole
	 */
	public final void setSchachtsole(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal schachtsole)
	{
		getMendixObject().setValue(context, MemberNames.Schachtsole.toString(), schachtsole);
	}

	/**
	 * @return value of MaxVerlust
	 */
	public final java.math.BigDecimal getMaxVerlust()
	{
		return getMaxVerlust(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxVerlust
	 */
	public final java.math.BigDecimal getMaxVerlust(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaxVerlust.toString());
	}

	/**
	 * Set value of MaxVerlust
	 * @param maxverlust
	 */
	public final void setMaxVerlust(java.math.BigDecimal maxverlust)
	{
		setMaxVerlust(getContext(), maxverlust);
	}

	/**
	 * Set value of MaxVerlust
	 * @param context
	 * @param maxverlust
	 */
	public final void setMaxVerlust(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal maxverlust)
	{
		getMendixObject().setValue(context, MemberNames.MaxVerlust.toString(), maxverlust);
	}

	/**
	 * @return value of IstVerlust
	 */
	public final java.math.BigDecimal getIstVerlust()
	{
		return getIstVerlust(getContext());
	}

	/**
	 * @param context
	 * @return value of IstVerlust
	 */
	public final java.math.BigDecimal getIstVerlust(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IstVerlust.toString());
	}

	/**
	 * Set value of IstVerlust
	 * @param istverlust
	 */
	public final void setIstVerlust(java.math.BigDecimal istverlust)
	{
		setIstVerlust(getContext(), istverlust);
	}

	/**
	 * Set value of IstVerlust
	 * @param context
	 * @param istverlust
	 */
	public final void setIstVerlust(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal istverlust)
	{
		getMendixObject().setValue(context, MemberNames.IstVerlust.toString(), istverlust);
	}

	/**
	 * @return value of _bestanden
	 */
	public final java.lang.Boolean get_bestanden()
	{
		return get_bestanden(getContext());
	}

	/**
	 * @param context
	 * @return value of _bestanden
	 */
	public final java.lang.Boolean get_bestanden(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._bestanden.toString());
	}

	/**
	 * Set value of _bestanden
	 * @param _bestanden
	 */
	public final void set_bestanden(java.lang.Boolean _bestanden)
	{
		set_bestanden(getContext(), _bestanden);
	}

	/**
	 * Set value of _bestanden
	 * @param context
	 * @param _bestanden
	 */
	public final void set_bestanden(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _bestanden)
	{
		getMendixObject().setValue(context, MemberNames._bestanden.toString(), _bestanden);
	}

	/**
	 * @return value of Score
	 */
	public final java.math.BigDecimal getScore()
	{
		return getScore(getContext());
	}

	/**
	 * @param context
	 * @return value of Score
	 */
	public final java.math.BigDecimal getScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Score.toString());
	}

	/**
	 * Set value of Score
	 * @param score
	 */
	public final void setScore(java.math.BigDecimal score)
	{
		setScore(getContext(), score);
	}

	/**
	 * Set value of Score
	 * @param context
	 * @param score
	 */
	public final void setScore(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal score)
	{
		getMendixObject().setValue(context, MemberNames.Score.toString(), score);
	}

	/**
	 * @return value of Uhrzeit
	 */
	public final java.util.Date getUhrzeit()
	{
		return getUhrzeit(getContext());
	}

	/**
	 * @param context
	 * @return value of Uhrzeit
	 */
	public final java.util.Date getUhrzeit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Uhrzeit.toString());
	}

	/**
	 * Set value of Uhrzeit
	 * @param uhrzeit
	 */
	public final void setUhrzeit(java.util.Date uhrzeit)
	{
		setUhrzeit(getContext(), uhrzeit);
	}

	/**
	 * Set value of Uhrzeit
	 * @param context
	 * @param uhrzeit
	 */
	public final void setUhrzeit(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date uhrzeit)
	{
		getMendixObject().setValue(context, MemberNames.Uhrzeit.toString(), uhrzeit);
	}

	/**
	 * @return value of Dauer
	 */
	public final java.lang.Integer getDauer()
	{
		return getDauer(getContext());
	}

	/**
	 * @param context
	 * @return value of Dauer
	 */
	public final java.lang.Integer getDauer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Dauer.toString());
	}

	/**
	 * Set value of Dauer
	 * @param dauer
	 */
	public final void setDauer(java.lang.Integer dauer)
	{
		setDauer(getContext(), dauer);
	}

	/**
	 * Set value of Dauer
	 * @param context
	 * @param dauer
	 */
	public final void setDauer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dauer)
	{
		getMendixObject().setValue(context, MemberNames.Dauer.toString(), dauer);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Schacht_Einsatz
	 */
	public final fels.proxies.Einsatz getSchacht_Einsatz() throws com.mendix.core.CoreException
	{
		return getSchacht_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of Schacht_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getSchacht_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Schacht_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Schacht_Einsatz
	 * @param schacht_einsatz
	 */
	public final void setSchacht_Einsatz(fels.proxies.Einsatz schacht_einsatz)
	{
		setSchacht_Einsatz(getContext(), schacht_einsatz);
	}

	/**
	 * Set value of Schacht_Einsatz
	 * @param context
	 * @param schacht_einsatz
	 */
	public final void setSchacht_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz schacht_einsatz)
	{
		if (schacht_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.Schacht_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Schacht_Einsatz.toString(), schacht_einsatz.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Schacht_Pruefer
	 */
	public final fels.proxies.Mitarbeiter getSchacht_Pruefer() throws com.mendix.core.CoreException
	{
		return getSchacht_Pruefer(getContext());
	}

	/**
	 * @param context
	 * @return value of Schacht_Pruefer
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Mitarbeiter getSchacht_Pruefer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Mitarbeiter result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Schacht_Pruefer.toString());
		if (identifier != null) {
			result = fels.proxies.Mitarbeiter.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Schacht_Pruefer
	 * @param schacht_pruefer
	 */
	public final void setSchacht_Pruefer(fels.proxies.Mitarbeiter schacht_pruefer)
	{
		setSchacht_Pruefer(getContext(), schacht_pruefer);
	}

	/**
	 * Set value of Schacht_Pruefer
	 * @param context
	 * @param schacht_pruefer
	 */
	public final void setSchacht_Pruefer(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Mitarbeiter schacht_pruefer)
	{
		if (schacht_pruefer == null) {
			getMendixObject().setValue(context, MemberNames.Schacht_Pruefer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Schacht_Pruefer.toString(), schacht_pruefer.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return schachtMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Schacht that = (fels.proxies.Schacht) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
