// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class SelectionHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject selectionHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.SelectionHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NumberOfSelectedLeistungen("NumberOfSelectedLeistungen"),
		SelectionHelper_Einsatz("Fels.SelectionHelper_Einsatz");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SelectionHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SelectionHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject selectionHelperMendixObject)
	{
		if (selectionHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, selectionHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.selectionHelperMendixObject = selectionHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.SelectionHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.SelectionHelper(context, mendixObject);
	}

	public static fels.proxies.SelectionHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.SelectionHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of NumberOfSelectedLeistungen
	 */
	public final java.lang.Integer getNumberOfSelectedLeistungen()
	{
		return getNumberOfSelectedLeistungen(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfSelectedLeistungen
	 */
	public final java.lang.Integer getNumberOfSelectedLeistungen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfSelectedLeistungen.toString());
	}

	/**
	 * Set value of NumberOfSelectedLeistungen
	 * @param numberofselectedleistungen
	 */
	public final void setNumberOfSelectedLeistungen(java.lang.Integer numberofselectedleistungen)
	{
		setNumberOfSelectedLeistungen(getContext(), numberofselectedleistungen);
	}

	/**
	 * Set value of NumberOfSelectedLeistungen
	 * @param context
	 * @param numberofselectedleistungen
	 */
	public final void setNumberOfSelectedLeistungen(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofselectedleistungen)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfSelectedLeistungen.toString(), numberofselectedleistungen);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SelectionHelper_Einsatz
	 */
	public final fels.proxies.Einsatz getSelectionHelper_Einsatz() throws com.mendix.core.CoreException
	{
		return getSelectionHelper_Einsatz(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectionHelper_Einsatz
	 * @throws com.mendix.core.CoreException
	 */
	public final fels.proxies.Einsatz getSelectionHelper_Einsatz(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fels.proxies.Einsatz result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SelectionHelper_Einsatz.toString());
		if (identifier != null) {
			result = fels.proxies.Einsatz.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SelectionHelper_Einsatz
	 * @param selectionhelper_einsatz
	 */
	public final void setSelectionHelper_Einsatz(fels.proxies.Einsatz selectionhelper_einsatz)
	{
		setSelectionHelper_Einsatz(getContext(), selectionhelper_einsatz);
	}

	/**
	 * Set value of SelectionHelper_Einsatz
	 * @param context
	 * @param selectionhelper_einsatz
	 */
	public final void setSelectionHelper_Einsatz(com.mendix.systemwideinterfaces.core.IContext context, fels.proxies.Einsatz selectionhelper_einsatz)
	{
		if (selectionhelper_einsatz == null) {
			getMendixObject().setValue(context, MemberNames.SelectionHelper_Einsatz.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SelectionHelper_Einsatz.toString(), selectionhelper_einsatz.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return selectionHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.SelectionHelper that = (fels.proxies.SelectionHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
