// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fels.proxies;

public class Urlaubsfilter implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject urlaubsfilterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Fels.Urlaubsfilter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Year("Year"),
		Holidays("Holidays");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Urlaubsfilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Urlaubsfilter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject urlaubsfilterMendixObject)
	{
		if (urlaubsfilterMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, urlaubsfilterMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.urlaubsfilterMendixObject = urlaubsfilterMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static fels.proxies.Urlaubsfilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fels.proxies.Urlaubsfilter(context, mendixObject);
	}

	public static fels.proxies.Urlaubsfilter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fels.proxies.Urlaubsfilter.initialize(context, mendixObject);
	}

	/**
	 * @return value of Year
	 */
	public final java.util.Date getYear()
	{
		return getYear(getContext());
	}

	/**
	 * @param context
	 * @return value of Year
	 */
	public final java.util.Date getYear(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Year.toString());
	}

	/**
	 * Set value of Year
	 * @param year
	 */
	public final void setYear(java.util.Date year)
	{
		setYear(getContext(), year);
	}

	/**
	 * Set value of Year
	 * @param context
	 * @param year
	 */
	public final void setYear(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date year)
	{
		getMendixObject().setValue(context, MemberNames.Year.toString(), year);
	}

	/**
	 * @return value of Holidays
	 */
	public final java.lang.Integer getHolidays()
	{
		return getHolidays(getContext());
	}

	/**
	 * @param context
	 * @return value of Holidays
	 */
	public final java.lang.Integer getHolidays(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Holidays.toString());
	}

	/**
	 * Set value of Holidays
	 * @param holidays
	 */
	public final void setHolidays(java.lang.Integer holidays)
	{
		setHolidays(getContext(), holidays);
	}

	/**
	 * Set value of Holidays
	 * @param context
	 * @param holidays
	 */
	public final void setHolidays(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer holidays)
	{
		getMendixObject().setValue(context, MemberNames.Holidays.toString(), holidays);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return urlaubsfilterMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fels.proxies.Urlaubsfilter that = (fels.proxies.Urlaubsfilter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
