// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} parameter
 * @returns {Promise.<void>}
 */
export async function JavaScript_action(parameter) {
	// BEGIN USER CODE
	const canvas = document.getElementById("drawingCanvas");
    const ctx = canvas.getContext("2d");
	const img = new Image();
	img.src = "http://localhost:8080/file?guid=14918173765664995&amp;changedDate=1740322876121&amp;name=Picture2.jpg";

	canvas.width = img.width;
        canvas.height = img.height;
        ctx.drawImage(img, 0, 0);
	let zeichnen = false;

    canvas.addEventListener("mousedown", () => zeichnen = true);
    canvas.addEventListener("mouseup", () => {
        zeichnen = false;
        ctx.beginPath(); // Neuen Pfad starten
    });
    canvas.addEventListener("mousemove", zeichne);

    function zeichne(event) {
        if (!zeichnen) return;

        ctx.lineWidth = 3;
        ctx.lineCap = "round";
        ctx.strokeStyle = "red"; // Farbe der Linie

        ctx.lineTo(event.offsetX, event.offsetY);
        ctx.stroke();
        ctx.beginPath();
        ctx.moveTo(event.offsetX, event.offsetY);
    } 
	// END USER CODE
}
