// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package felstheme.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the FelsTheme module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder logiAsAdminBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FelsTheme.LogiAsAdmin");
		return builder;
	}

	public static void logiAsAdmin(IContext context)
	{
		logiAsAdminBuilder().execute(context);
	}
}
