// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_DeploymentType
{
	MendixPublicCloud(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mendix Public Cloud" } }),
	MendixPrivateCloud(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mendix for Private Cloud Connected" } }),
	MendixCloudDedicated(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mendix Cloud Dedicated" } }),
	Other(new java.lang.String[][] { new java.lang.String[] { "en_US", "Other" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_DeploymentType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "de_DE");
	}

	public java.lang.String getCaption()
	{
		return captions.get("de_DE");
	}
}
